### ISSUE TITLE
Support options for machine types

### ISSUE THREAD

**Issue by devimc** [clearcontainers/runtime#1001]
# Description of problem

Unable to specify options for machine types in configuration file

# Expected result

Qemu command line should have options for the machine type

```
qemu ... -machine virt,accel=kvm,gic-version=host,usb=off
```

where **gic-version=host,usb=off** are the options

# Actual result

```
qemu ... -machine virt,accel=kvm ....
```

# Solution

add **machine_options** in configuration file

**Comment by jodh-intel** [comment]
I'm not 100% clear on this. Currently, the runtime supports a `machine_accelerators=` config option. Those values get added to the `accel=` qemu option by the govmm package, so you could add `gic-version=host`, there I think?

@markdryan - or would we need (also) need changes to https://github.com/intel/govmm dyt?

**Comment by markdryan** [comment]
@jodh-intel We've just merged a related change to go-vmm.

https://github.com/intel/govmm/pull/9

**Comment by jodh-intel** [comment]
Thanks @markdryan, @devimc - I love it when that happens! :smile:

**Comment by GabyCT** [comment]
@devimc working on this :)
