### ISSUE TITLE
osbuilder

### ISSUE THREAD

**Issue by Oliverlyn** [clearcontainers/runtime#1004]
# Description of problem

(replace this text with the list of steps you followed)

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `cc-collect-data.sh` script, after you have
reviewed its content to ensure it does not contain any private information).

**Comment by grahamwhaley** [comment]
HI @Oliverlyn - I'm going to presume you know that you didn't post any actual details into the template form?

**Comment by jodh-intel** [comment]
Hi @Oliverlyn - If the problem relates to the runtime, please provide the data as specified by the template.

If the problem relates to `osbuilder`, please raise an issue here:

- https://github.com/clearcontainers/osbuilder/issues/new

**Comment by devimc** [comment]
duplicated https://github.com/clearcontainers/runtime/issues/1006 , closing issue
@Oliverlyn feel free to re-open it, if I'm wrong
