### ISSUE TITLE
osbuilder failed：“BDB0126 mmap: Invalid argument......”

### ISSUE THREAD

**Issue by Oliverlyn** [clearcontainers/runtime#1006]
# Description of problem
my OS is ubuntu16.04.
the kernel info: kernel-4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux.
I want to install cc as developer's mode follows "Developers Clear Containers 3.0 Install", but failed at the step "Build and install components-Agent". When I execute the cmmond "sudo -E make rootfs USE_DOCKER=true", something goes wrong here!
the failure infos as follows:
root@hera:/home/golang/src/github.com/clearcontainers/agent# cd $GOPATH/src/github.com/clearcontainers/osbuilder
root@hera:/home/golang/src/github.com/clearcontainers/osbuilder# sudo -E make rootfs USE_DOCKER=true
mkdir -p /home/golang/src/github.com/clearcontainers/osbuilder/workdir
/bin/sh: 1: curl: not found
cd scripts; \
docker build  --build-arg GO_VERSION= -t cc-osbuilder .
Sending build context to Docker daemon  17.92kB
Step 1/9 : From fedora:27
 ---> 422dc563ca32
Step 2/9 : RUN dnf install -y qemu-img parted gdisk make gcc bc git e2fsprogs libudev-devel pkgconfig
 ---> Running in 61a6f9eb7119
BDB0126 mmap: Invalid argument
handle_proxy_response:616:Error response received from proxy at /run/virtcontainers/pods/61a6f9eb71199caf2170a28827389589e02111dfe56fccd4facd46eac96dbe72/proxy.sock: {"msg":"vm: unknown token wF8jaR4LqkAxwLKbhZtUy88pthV9LD33T3WPhDuPiYg="}

/usr/libexec/clear-containers/cc-shim: Shim received an error in responseto ConnectShim command, exitingThe command '/bin/sh -c dnf install -y qemu-img parted gdisk make gcc bc git e2fsprogs libudev-devel pkgconfig' returned a non-zero code: 1
Makefile:114: recipe for target 'docker-build' failed
make: *** [docker-build] Error 1

I don't know how to solve the problems, I need help!
thanks!

**Comment by grahamwhaley** [comment]
Hi @Oliverlyn . Thanks for the extra info.

I see two potential things there we should look at first.

1) `/bin/sh: 1: curl: not found`
Can you check that you do have `curl` installed, and if not, please install it :-)

2) `BDB0126 mmap: Invalid argument`
This is an error I have seen if you have `cc-runtime` as your default docker runtime. Can you do a `docker info` and look for the `Default Runtime` line - this needs to be `runc` for osbuilder to work.

/cc @jcvenegas

**Comment by devimc** [comment]
@Oliverlyn this is a know issue, as a workaround you can use qemu >= 2.10 or use runC as default runtime.

more info about the issue https://github.com/clearcontainers/runtime/issues/868

**Comment by devimc** [comment]
probably we should close this issue since it was already reported here https://github.com/clearcontainers/runtime/issues/868

**Comment by Oliverlyn** [comment]
thx, long time! OK,I will close the issue.
