### ISSUE TITLE
Package 3.0 components

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#103]
All 3.0 components need to be packaged and distributed through OBS.

TBD: Do we want a new OBS repo for them, or do we want to overwrite the exisiting one ?

**Comment by dlespiau** [comment]
We want a new repo. We're already versioning them, so we can just add a 3.0 one next to the others.

**Comment by gorozco1** [comment]
@sameo @dlespiau could you please tag the components in github.com/clearlinux (runtime, shim, proxy to enable packaging @ OBS. **3.0.0-alpha0** might work

**Comment by gorozco1** [comment]
@sameo @dlespiau Nevermind, I will use my own clones and see whtat's the best approach for taggging

**Comment by sameo** [comment]
@gorozco1 Any updates on that one ?

**Comment by amyleeland** [comment]
@gorozco1 is this complete?

**Comment by gorozco1** [comment]
@amyleeland yes, sorry for not closing weeks ago completed 

http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/
