### ISSUE TITLE
[Proposal] [RFC] Start VMs with 1 vCPU

### ISSUE THREAD

**Issue by devimc** [clearcontainers/runtime#1032]
# Description
By default the runtime starts the VM with the same number of physical cores, sometimes when the number of physical cores is not too big, the boot time and memory consumption is not a problem, but when the number of physical cores is big, the boot time and memory footprint increase [*]:

**time to create and destroy a container**
```md
+-----------------------+----------------+---------------------+
|  Container CPUs_Mem   |  time(s)       | Memory footprint(Mb)|
+=======================+================+=====================+
|  2cpus_2gb            | 1.7401         | 68.36               |
+-----------------------+----------------+---------------------+
|  88cpus_2gb           | 2.34915        | 166.008008          |
+-----------------------+----------------+---------------------+
```

Other point to consider is the fact that the runtime must have support to update container's resources dynamically, and the only way to achieve this is through QEMU hot-plug and cgroups.
The VM should start with the minimum number of resources (CPU and Memory) to allow the runtime hot plug and unplug resources as needed.

The difference between starting the container with 1 and 2 vCPUs is not considerable [+]

**time to create and destroy a container**
```md
+--------------------+----------------+
|  Container vCPUs   |  time(s)       |
+====================+================+
|  1                 | 1.017          |
+--------------------+----------------+
|  2                 | 1.0129         |
+--------------------+----------------+
```

[*] thanks to @grahamwhaley  for the data
[+] using `launch_times.sh -i debian -n 100 -r cc-runtime`

# Proposal
- [ ] Change `default_vcpus` to 1 in the runtime configuration file 

Currently when a container with CPU constrains is created using docker, the VM starts with a different number of vcpus than the value specified by `default_vcpus`, this was an expected behaviour but with https://github.com/containers/virtcontainers/pull/512 a CPU cgroup is created inside the VM limiting the CPU usage of the container, hence doesn't matter if the VM has 89 vCPUs the container only can use the CPUs of the cgroup.

- [x] Always start the VM with the number of vCPUs specified by `default_vcpus`

**Comment by devimc** [comment]
cc @jodh-intel @grahamwhaley @jcvenegas @sameo @sboeuf

**Comment by grahamwhaley** [comment]
I'll note - I think that first table shows 'time to create and destroy a container', and the second table shows 'time to get to the workoad' - which is fine (just pointing out why there is a bit of a time disparity).

Given the pretty tiny % difference to get to the workload between 1 and 2 vCPUs, it looks fine to me to default to 1. I would request that maybe we add a config var to the config toml file to allow the user to over-ride the default if they so need or desire at some later time?

**Comment by devimc** [comment]
@grahamwhaley thanks, let me update the description

**Comment by devimc** [comment]
@grahamwhaley 

> I would request that maybe we add a config var to the config toml file to allow the user to over-ride the default if they so need or desire at some later time?

I would like to start the VM with more than 1 vCPU (cold plug), because could plugged resources can not be removed later,

**Comment by grahamwhaley** [comment]
@devimc Sure. But...
- if the end-user has a case where they know they want to always start with 2 or 4 or n containers, we should allow them to set it up for that (and document the caveats etc.)
- iirc, you are mainly thinking about the k8s pod case, yes - but, this will also affect the docker use case, so we should not forget that either, yes?

**Comment by devimc** [comment]
@grahamwhaley yes, now I understand your point

**Comment by devimc** [comment]
proposal updated, thanks

**Comment by sameo** [comment]
cc @mcastelino
