### ISSUE TITLE
Find a way to display the agent version

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#1055]
As mentioned https://github.com/clearcontainers/tests/issues/944#issuecomment-371157669, the runtime does *not* display the agent version, although the output of `cc-env` suggests it should/tries to:

```
$ cc-runtime cc-env|grep -A 2 Agent
[Agent]
  Type = "hyperstart"
  Version = "<<unknown>>"
```

The best strategy would seem to be to bind-mount the image (using `losetup`+`mount`) and run `cc-agent --version` now that https://github.com/clearcontainers/agent/pull/213 has landed.

The question though is where we should run this:

1. In the runtime

   This would allow the `cc-env` output to display the correct `Agent.Version=`.

1. In [`cc-collect-data.sh`](https://github.com/clearcontainers/runtime/blob/master/data/collect-data.sh.in)

   If we do this, we need to remove the `Agent.Version=` from the runtime.

Option (1) seems logical but is a bit... brace yourself for a very technical term... "*yucky*". That said:

- such code wouldn't be part of the main runtime lifecycle flows.
- we already have precedent for doing similar things as `cc-check` calls `modinfo(8)`.

wdyt @sboeuf, @sameo, @grahamwhaley, @mcastelino? Should we take a vote on this? :smile:

**Comment by sboeuf** [comment]
I'd say option 2 since I don't like that we have to mount the image so that we can find the agent version from cc-runtime.
`cc-collect-data.sh` is a separate script, which might be more appropriate for this specific mounting operation.

**Comment by jodh-intel** [comment]
Sounds reasonable. I'll update the script...
