### ISSUE TITLE
docker args --cpus or --cpu-quota/--cpu-period isn't working

### ISSUE THREAD

**Issue by linxiulei** [clearcontainers/runtime#1088]
# Description of problem

I found it can't specify the number of cpu anymore, which I do at clearcontainers v2

docker run --cpus 16 busybox /bin/sh

Enter the container and see "cat /proc/cpuinfo", only 1 vcpu displays. There was a commit https://github.com/containers/virtcontainers/pull/541/commits/67fcb6dcb27842fa75975215ad820a8551440ab1, which honors the --cpus, but it was refactored to `Constraint`, then has nothing to do with VM cpus

I have to change config `default_vcpus = 1` to let vm have more than 1 vcpu, though it can't reach more than 8. I do know it is related to kernel, which I use what clearcontainers provides too. why clearcontainer limits kernel with `CONFIG_NR_CPUS=8`? Does it have any improvement?

# Expected result

`docker run --cpus 16 busybox /bin/sh`

`docker run exec $id cat /proc/cpuinfo`

show 16 vcpu

# Actual result

`docker run --cpus 16 busybox /bin/sh`

`docker run exec $id cat /proc/cpuinfo`

show 1 vcpu

---

# Meta details

Running `cc-collect-data.sh` version `3.0.22 (commit 4b569ac)` at `2018-03-29.20:40:13.377170283+0800`.

---

Runtime is `/usr/bin/cc-runtime`.

# `cc-env`

Output of "`/usr/bin/cc-runtime cc-env`":
```
[Meta]
  Version = "1.0.9"

[Runtime]
  Debug = false
  [Runtime.Version]
    Semver = "3.0.22"
    Commit = "4b569ac"
    OCI = "1.0.1"
  [Runtime.Config]
    Path = "/etc/clear-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.7.1 (), Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/local/bin/qemu-system-x86_64"
  Debug = false
  BlockDeviceDriver = "virtio-scsi"

[Image]
  Path = "/usr/share/clear-containers/clear-containers.img"

[Kernel]
  Path = "/usr/share/clear-containers/vmlinuz-4.9.47-78.1.alios7.container"
  Parameters = ""

[Proxy]
  Type = "ccProxy"
  Version = "Version: 3.0.19+git.318ac7e"
  Path = "/usr/libexec/clear-containers/cc-proxy"
  Debug = true

[Shim]
  Type = "ccShim"
  Version = "shim version: 3.0.19 (commit: 557fe9b)"
  Path = "/usr/libexec/clear-containers/cc-shim"
  Debug = false

[Agent]
  Type = "hyperstart"
  Version = "<<unknown>>"

[Host]
  Kernel = "4.9.54-005.ali3000.alios7.x86_64"
  Architecture = "amd64"
  VMContainerCapable = true
  [Host.Distro]
    Name = "CentOS Linux Server"
    Version = "7.2"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz"
```

---

# Runtime config files

## Runtime default config files

```
/etc/clear-containers/configuration.toml
/usr/share/defaults/clear-containers/configuration.toml
```

## Runtime config file contents

Output of "`cat "/etc/clear-containers/configuration.toml"`":
```
[hypervisor.qemu]
path = "/usr/local/bin/qemu-system-x86_64"
kernel = "/usr/share/clear-containers/vmlinuz.container"
image = "/usr/share/clear-containers/clear-containers.img"
machine_type = "pc"
kernel_params = ""
firmware = ""
machine_accelerators=""
default_vcpus = 1
default_bridges = 1
disable_block_device_use = true
#block_device_driver = "virtio-scsi"

[proxy.cc]
enable_debug = true
path = "/usr/libexec/clear-containers/cc-proxy"

[shim.cc]
path = "/usr/libexec/clear-containers/cc-shim"


[agent.cc]

[runtime]
internetworking_model="macvtap"
```
Config file `/usr/share/defaults/clear-containers/configuration.toml` not found

---

# Agent

version:
```
unknown
```

---

# Logfiles

**Comment by grahamwhaley** [comment]
Hi @linxiulei I think @devimc might be best placed to help here (but it might not be until early next week - public holidays etc.).
I don't think the `--cpus` is quite as simple as a 1:1 mapping to `vcpus` - at least for `runc` it is not, which I think uses the CFS and cgroup settings to 'allocate CPU resource' (https://docs.docker.com/config/containers/resource_constraints/#cpu).

Thus, we should probably define and write down what algo and method we use to map `--cpus` to VM vCPUs.

Having said that, if you set `--cpus=8`, and you only get one vcpu in the VM, then that can't really be right, can it :-)

**Comment by linxiulei** [comment]
Hi @grahamwhaley thank you for reply

I agree with that we should've a method to with it. However the issue is, no matter what you define (with --cpu-quota/--cpu-period etc), at least I should be able to specify how much cpu or correspond performance to be allocated to a container. Apparently, with this issue I have no choice.

Is it considered as a bug?

**Comment by linxiulei** [comment]
I think it has been fixed
