### ISSUE TITLE
Kernel build failing due to elfutils-libelf-devel being missing

### ISSUE THREAD

**Issue by t3hmrman** [clearcontainers/runtime#1103]
# Description of problem

Attempting to build the kernel causes an error noting that `elfutils-libelf-devel` is missing

# Expected result

Kernel build

# Actual result

Error during the kernel build

**Comment by devimc** [comment]
Hi @t3hmrman we are no more supporting this project, please use kata-containers https://github.com/kata-containers/runtime/

**Comment by t3hmrman** [comment]
hi @devimc I see -- I actually made this ticket in the wrong repo however, I meant to make it in `clearcontainers/osbuilder`, for the [PR I have open there](https://github.com/clearcontainers/osbuilder/pull/53)
