### ISSUE TITLE
Kill --all does not stop the VM

### ISSUE THREAD

**Issue by devimc** [clearcontainers/runtime#114]
```
CONTNAME=random
RUNTIME="./cc-runtime"
${RUNTIME} --log runtime.log create --pid-file ${BUNDLE}/pid --bundle ${BUNDLE}  --console $(tty) ${CONTNAME}
${RUNTIME} --log runtime.log start ${CONTNAME}
sleep 5
${RUNTIME} --log runtime.log kill --all ${CONTNAME} 15
```

**Comment by devimc** [comment]
similar issue https://github.com/clearcontainers/runtime/issues/5

**Comment by jodh-intel** [comment]
We need to ensure the correct behaviour for all possible signal values, not just `SIGTERM`.

**Comment by devimc** [comment]
still occurs

```
# cc-runtime version
   cc-runtime  : 3.0.0-alpha.4
   commit   : 5762bc3de4b01a69fa9d756e95ffae1a26b351d7
   OCI specs: 1.0.0-rc5
```

**Comment by devimc** [comment]
related to #343

**Comment by sboeuf** [comment]
Ok but are we sure that we want the VM to be killed when we do `cc-runtime kill --all` ? I mean we are talking about the VM here so we don't have reference with runc for this point.
I mean usually after a kill you call into `cc-runtime delete` and it will do the job to remove the VM.

**Comment by devimc** [comment]
@sboeuf no, I think this is an issue that currently we have
I noticed in 2.1.x that docker is able to identify (I guess it uses namespaces) what process were spawned by cor or runc, therefore when kill signal is sent docker expects all process to be killed, if not  then docker will kill them, for this reason we don't face this issue under docker.

**Comment by jodh-intel** [comment]
Re-reading the spec (which of course doesn't specify `--all`), "the spirit" of the `kill` command in this context would be to simply kill all processes in the container and have the VM torn down in `delete`. Snippets from [1]:

```
kill:
  This operation MUST send the specified signal to the process in the container.

delete:
  Deleting a container MUST delete the resources that were created during the create step.
```
[1] - https://github.com/opencontainers/runtime-spec/blob/master/runtime.md

**Comment by devimc** [comment]
after analyze/debug docker behavior, I agree with @jodh-intel and @sboeuf kill command must kill the processes in the container, this is not a problem in docker because it calls to runtime kill + delete
thanks @sboeuf

**Comment by sboeuf** [comment]
@devimc no problem ! Always good to brainstorm on these things ;)
