### ISSUE TITLE
improve debug behaviour

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/runtime#125]
_From @jodh-intel on February 17, 2017 17:8_

Since docker does not allow options to be passed to the hypervisor, enabling runtime debugging is awkward [1].

Rather than having to reconfigure docker to use the `cc-oci-runtime.sh` helper utility to enable debug, we could control debug via environment variables. Something like:

```
$ docker run --env='["COR_DEBUG" : "enabled", "COR_DEBUG_DIR": "/tmp" ]' -ti busybox ...
```

The best approach might be to only have one environment variable, pointing to a configuration file:

```
$ docker run --e COR_CONFIG_FILE=/etc/cc-oci-runtime/cc-oci-runtime.cfg -ti busybox ...
```

We could even drop the variable and just have the runtime check a list of well-known directories, looking for a `cc-oci-runtime.cfg` configuration file.
 
----
[1] - documented at https://github.com/01org/cc-oci-runtime/wiki/Debugging.

_Copied from original issue: 01org/cc-oci-runtime#680_

**Comment by dlespiau** [comment]
This is now an option in a config file. I think that fit the bill.
