### ISSUE TITLE
Find a way to propagate error messages from runtime to docker

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#128]
_From @dlespiau on November 2, 2016 12:33_

Right now, when the runtime fails to start a container for whatever reason (we weren't able to start qemu, find the kernel or image, ...) the only feedback containerd and docker gives back to the user is "container not started", which isn't very helpful and people needs extra guidance and manual steps to debug the issue.

We should try to find a way to propagate our error messages to containerd, then to docker. This may mean docker/containerd changes.

_Copied from original issue: 01org/cc-oci-runtime#364_

**Comment by sameo** [comment]
_From @jodh-intel on November 2, 2016 13:46_

Agreed.

Related: we could also explore the idea of logging direct to syslog for messages `>= G_LOG_LEVEL_WARNING` so that atleast users will see something in the journal (currently we only log to syslog if the logging subsystem itself fails to generate a log entry).

**Comment by sameo** [comment]
_From @jodh-intel on April 12, 2017 7:38_

Related: #680.

**Comment by jodh-intel** [comment]
Docker has fixed this for us.

For example, if I force a runtime failure by removing the config file:

```
$ cc-runtime version
cc-runtime  : 3.0.5
   commit   : 40047b5e21f8dde99caea91b5096c4ab360e4a27
   OCI specs: 1.0.0-dev
$ sudo rm  /usr/share/defaults/clear-containers/configuration.toml
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:20:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
$ sudo docker run -ti busybox true

docker: Error response from daemon: oci runtime error: Cannot find usable config file (config file "/etc/clear-containers/configuration.toml" unresolvable: file /etc/clear-containers/configuration.toml does not exist, config file "/usr/share/defaults/clear-containers/configuration.toml" unresolvable: file /usr/share/defaults/clear-containers/configuration.toml does not exist).
```
