### ISSUE TITLE
Run and delete several containers reduce the boot time progressively  

### ISSUE THREAD

**Issue by devimc** [clearcontainers/runtime#133]
```
for i in `seq 0 200 `; do time docker run --rm --runtime=cc30 -ti busybox true  ; done
```

starts with a real time of ```0.802s``` and ends with ```0m5.295s```!
seems like the pod directory is not cleaned and the function ```ListPod()``` takes a long time to return

**Comment by sboeuf** [comment]
@devimc Ah yes I think you forgot to call the `vc.StopPod()` and `vc.DeletePod()` in your run implementation, right ?

**Comment by devimc** [comment]
@sboeuf nop, I'm using docker and docker uses (create+start)

**Comment by sboeuf** [comment]
@devimc Ah okay then you should modify the script to make it remove the container created, shouldn't you ?
But I agree that 5.295s sounds a lot. We should investigate why ListPod() is taking so much time.

**Comment by devimc** [comment]
@sboeuf it takes long time to return because there a lot of pods in ```/var/lib/virtcontainers/pods/```
and int this chunk of code the for iterates a lot of times
```
for _, podID := range podsID {
	podStatus, err := StatusPod(podID)
	if err != nil {
		continue
	}

	podStatusList = append(podStatusList, podStatus)
}
```

**Comment by devimc** [comment]
@sboeuf seems like the same error is present in the ```run``` command, I added the calls to ```vc.StopPod()``` and ```vc.DeletePod()``` and the issue has gone , but it still occurs in docker
