### ISSUE TITLE
Support having a prefix in our installation targets

### ISSUE THREAD

**Issue by dlespiau** [clearcontainers/runtime#142]
That's the way packages are usually configured with a path to be installed in. We should have one so distros can configure where they want the runtime files installed (and so we can install the runtime in a separate prefix from the system one for development). Additionally each directory (BINDIR, SYSCONFDIR, ...) should be individually overridable.

**Comment by jodh-intel** [comment]
Added by 03e3caf0e451cf565da05fb5c1899187684f608d.
