### ISSUE TITLE
Enable package building for different distros in OBS

### ISSUE THREAD

**Issue by gorozco1** [clearcontainers/runtime#152]
We need to enable package building for different distros with cc 3.0 like we do with CC 2.1

**Comment by sameo** [comment]
@gorozco1 Could we please make that one a high priority ? The sooner we allow people to easily deploy Clear Containers 3.0, the better. And it's now in a state where it's ready to be tested by more than our core team.

**Comment by dlespiau** [comment]
This is a duplicate of #103. Close this one as it's newer.
