### ISSUE TITLE
exec is broken after the latest re-vendor

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#155]
Commit c9cb65c246ccece7cfc53839d6e0a48b2c9228f3 from #146 appears to have broken `exec`:

```
$ sudo docker exec -ti $(docker ps -q) /bin/true
rpc error: code = 2 desc = oci runtime error: json: cannot unmarshal array into Go struct field Process.capabilities of type specs.LinuxCapabilities
```

**Comment by dlespiau** [comment]
we need testing :(

**Comment by jodh-intel** [comment]
`+<very_large_number>` :((

**Comment by sboeuf** [comment]
I more than agree with that ! We are currently only testing that docker run busybox ifconfig works but we need tests for every command. Even very basic tests will be fine as long as we make sure that all commands are covered.
BTW, here is the fix: https://github.com/clearcontainers/runtime/pull/156

**Comment by sboeuf** [comment]
Well, that's the purpose of clearcontainers/tests. But I think that we should temporary add a few tests to semaphore CI so that we can detect if we break something while we are waiting to get the full testing ready.

**Comment by jodh-intel** [comment]
I know :) But we haven't actually added the bats tests there yet.

Yep - we need something sooner rather than later.

**Comment by dlespiau** [comment]
Should we close this now that https://github.com/clearcontainers/runtime/pull/156 is in?

**Comment by sboeuf** [comment]
yes

**Comment by jodh-intel** [comment]
We really should set up https://github.com/clearcontainers/tests/tree/master/cmd/checkcommits for this repo too ;-)
