### ISSUE TITLE
Write some instructions for a developer to get started with 3.0

### ISSUE THREAD

**Issue by dlespiau** [clearcontainers/runtime#157]

**Comment by wuzhy** [comment]
where is the output? or how to find these instructions?

**Comment by dlespiau** [comment]
This task hasn't started so there's no documentation yet. As part of doing this, where to find the instructions very visible in the README.md and the URL should be part of the comment closing this issue.

**Comment by wuzhy** [comment]
got it, thanks. It will be appreciated if a guide about how to play with cc 3.0 on CentOS is provided.
