### ISSUE TITLE
failed to run clear container standalone

### ISSUE THREAD

**Issue by devimc** [clearcontainers/runtime#158]
## command 
```
${RUNTIME} --debug --log runtime.log run --pid-file "${BUNDLE}/pid" --bundle "${BUNDLE}" --console $(tty) "${CONTNAME}"
```

## current output:
```
fork/exec /home/X/gopath/src/github.com/clearcontainers/shim/cc-shim: operation not permitted
```

## expected output:
```
sh-4.3#
```

the issue is that terminal is already the controlling terminal of a different session group, to allow spawned process use assigned terminal we have to steal it form the session group (TIOCSCTTY with arg=1)

**Comment by devimc** [comment]
proposed fix https://github.com/devimc/go/commit/559e40cd92c0fa447d997d680adf170aec2295ae

**Comment by devimc** [comment]
filed an issue in golang/go https://github.com/golang/go/issues/20454

**Comment by dlespiau** [comment]
Seems like the easier way to go about this is to not support `--console $(tty)`. We could do what runc does when specifying `/dev/ptmx` as console path.

**Comment by devimc** [comment]
closing this issue because we can't support ```--console $(tty)``` since this is a limitation of golang (processes can't steal tty)
