### ISSUE TITLE
The VM *isn't* destroyed when cc container is removed

### ISSUE THREAD

**Issue by wuzhy** [clearcontainers/runtime#167]
When cc 3.0 container is removed, i found that its QEMU VM still is there. It isn't correct.
root     16190     1  0 May23 ?        00:00:26 /usr/local/bin/qemu-system-x86_64 -name pod-b7c352f00cb6c622de16b417d121086e43bd47f40a687b3bd62ac35b2c96ee3a -uuid 62376333-3532-6630-3063-623663363232 -machine pc-lite,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/virtcontainers/pods/b7c352f00cb6c622de16b417d121086e43bd47f40a687b3bd62ac35b2c96ee3a/monitor.sock,server,nowait -qmp unix:/run/virtcontainers/pods/b7c352f00cb6c622de16b417d121086e43bd47f40a687b3bd62ac35b2c96ee3a/ctrl.sock,server,nowait -m 2G,slots=2,maxmem=3G -smp 24,cores=24,threads=1,sockets=1 -device virtio-9p-pci,fsdev=ctr-9p-0,mount_tag=ctr-rootfs-0 -fsdev local,id=ctr-9p-0,path=/var/lib/docker/devicemapper/mnt/681d2867c24252034d831903466168612184d4e8437dbb9db23cbffbdd271ee6/rootfs,security_model=none -device virtio-serial-pci,id=serial0 -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/virtcontainers/pods/b7c352f00cb6c622de16b417d121086e43bd47f40a687b3bd62ac35b2c96ee3a/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/clear-containers/clear-containers.img,size=235929600 -device virtserialport,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch0,path=/tmp/hyper-pod-b7c352f00cb6c622de16b417d121086e43bd47f40a687b3bd62ac35b2c96ee3a.sock,server,nowait -device virtserialport,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -chardev socket,id=charch1,path=/tmp/tty-podb7c352f00cb6c622de16b417d121086e43bd47f40a687b3bd62ac35b2c96ee3a.sock,server,nowait -device virtio-9p-pci,fsdev=extra-9p-hyperShared,mount_tag=hyperShared -fsdev local,id=extra-9p-hyperShared,path=/tmp/hyper/shared/pods/b7c352f00cb6c622de16b417d121086e43bd47f40a687b3bd62ac35b2c96ee3a,security_model=none -device virtio-net-pci,netdev=network-0,mac=72:a2:69:9c:5d:e4 -netdev tap,id=network-0,ifname=tap0,downscript=no,script=no -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -kernel /usr/share/clear-containers/vmlinux.container -append root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k panic=1 console=hvc0 console=hvc1 initcall_debug init=/usr/lib/systemd/systemd systemd.unit=cc-agent.target iommu=off systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket cryptomgr.notests net.ifnames=0 quiet systemd.show_status=false

[root@192 ~]# cc-runtime --version
cc-runtime version runtime  : 3.0.0-alpha.0
   commit   : 95b78061b54b1d73b3aaad6e5c579860cae00b4d-dirty
   OCI specs: 1.0.0-rc5
[root@192 ~]#

**Comment by wuzhy** [comment]
Can anyone help look into this issue?

**Comment by dlespiau** [comment]
Could you include what you did so we can reproduce this more easily? is that with a `docker run` command?

**Comment by sboeuf** [comment]
Please provide more context about what you did, otherwise it will be complicated for us to help with that issue.

**Comment by wuzhy** [comment]
I set up a cc 3.0 env on CentOS 7.2, after a cc container was run, i only executed "docker rm -f containerid", and then this container was removed, but its VM is still there.

**Comment by egernst** [comment]
@sboeuf ; @wuzhy -- can we reproduce this on latest?  If not I think we should close?

**Comment by sboeuf** [comment]
I don't have the step to check this. Unless we get more context from @wuzhy, we can close this one.

**Comment by amyleeland** [comment]
@wuzhy We have not been able to reproduce this. If you have the steps please send them and we will look into this. IF you are seeing this on the latest release please re-open with steps on how to reproduce

**Comment by jodh-intel** [comment]
Also, please include the output from the following command if you can recreate:

```
$ cc-runtime cc-env
```
