### ISSUE TITLE
the user and group settings in config.json are not honoured.

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#17]
_From @jodh-intel on July 18, 2016 16:58_

Specifically, `process.user.uid`, `process.user.gid` and `process.additionalGids` are ignored.

See:
-  `clr_oci_create_container_workload()` in [src/oci.c](src/oci.c).
- https://github.com/opencontainers/runtime-spec/blob/master/config.md#user.

_Copied from original issue: 01org/cc-oci-runtime#20_

**Comment by sameo** [comment]
_From @jodh-intel on August 23, 2016 13:37_

It would make sense to handle #139 here too.

**Comment by sameo** [comment]
_From @jodh-intel on August 31, 2016 10:5_

Although the default user+group are `root`, docker 1.12 specifies `process.additionalGids=10` (`wheel`).

**Comment by amshinde** [comment]
Issue fixed and verified: https://github.com/clearcontainers/tests/pull/427
