### ISSUE TITLE
The docker failed to be started after cc 3.0 is reinstalled

### ISSUE THREAD

**Issue by wuzhy** [clearcontainers/runtime#172]
[root@192 runtime]# sh -x .ci/install_cc_runtime.sh
...
Redirecting to /bin/systemctl start  cc-proxy.service
Warning: cc-proxy.service changed on disk. Run 'systemctl daemon-reload' to reload units.

[root@192 runtime]# docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                   NAMES
8425e4f99464        preugistry.service.ucloud.cn/cicd/deploy_log   "/bin/sh -c 'cron && "   45 hours ago        Up 19 seconds       0.0.0.0:1514->514/tcp   lxh_log_1
[root@192 runtime]# docker ps -a
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS                            PORTS                   NAMES
772b3eb707c1        busybox                                        "/bin/sh"                37 hours ago        Exited (137) About a minute ago                           c2web
ba8dea7f1366        busybox                                        "/bin/sh"                37 hours ago        Exited (137) About a minute ago                           cweb
9ac96220087f        uhub.ucloud.cn/lxhtest1/ovs-plugin             "docker-ovs-plugin -d"   44 hours ago        Exited (0) 2 minutes ago                                  lxh_plugin_1
b5c6f106eb1f        uhub.ucloud.cn/lxhtest1/openvswitch:2.3.2      "/usr/bin/supervisord"   44 hours ago        Exited (0) 2 minutes ago                                  lxh_ovs_1
8425e4f99464        preugistry.service.ucloud.cn/cicd/deploy_log   "/bin/sh -c 'cron && "   45 hours ago        Up 22 seconds                     0.0.0.0:1514->514/tcp   lxh_log_1
965e67543a76        redis                                          "docker-entrypoint.sh"   11 days ago         Exited (0) 8 days ago                                     clearweb
a132cc4efe56        redis                                          "docker-entrypoint.sh"   11 days ago         Exited (0) 8 days ago                                     nauseous_swartz
1cd1c4a2dbaf        redis                                          "docker-entrypoint.sh"   11 days ago         Exited (0) 8 days ago                                     web
[root@192 runtime]# docker start 9ac96220087f b5c6f106eb1f
9ac96220087f
b5c6f106eb1f
[root@192 runtime]# docker start ba8dea7f1366 772b3eb707c1
Error response from daemon: Post http://%2Frun%2Fdocker%2Fplugins%2Fovs.sock/NetworkDriver.Join: http: ContentLength=301 with Body length 0
Error response from daemon: Post http://%2Frun%2Fdocker%2Fplugins%2Fovs.sock/NetworkDriver.Join: http: ContentLength=301 with Body length 0
Error: failed to start containers: ba8dea7f1366, 772b3eb707c1
[root@192 runtime]# docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                   NAMES
9ac96220087f        uhub.ucloud.cn/lxhtest1/ovs-plugin             "docker-ovs-plugin -d"   44 hours ago        Up About a minute                           lxh_plugin_1
b5c6f106eb1f        uhub.ucloud.cn/lxhtest1/openvswitch:2.3.2      "/usr/bin/supervisord"   44 hours ago        Up About a minute                           lxh_ovs_1
8425e4f99464        preugistry.service.ucloud.cn/cicd/deploy_log   "/bin/sh -c 'cron && "   45 hours ago        Up About a minute   0.0.0.0:1514->514/tcp   lxh_log_1
[root@192 runtime]# 
[root@192 runtime]# docker network rm mynet                                                    
mynet
[root@192 runtime]# 
[root@192 runtime]# sudo systemctl restart docker                                          
[root@192 runtime]# 
[root@192 runtime]# docker start 9ac96220087f b5c6f106eb1f
9ac96220087f
b5c6f106eb1f
[root@192 runtime]# sudo systemctl restart docker^C       
[root@192 runtime]# docker network create -d ovs mynet       
5cd7b7050fabf9ae7a584c838445c595e774023f721db2a33071eed044faa14a
[root@192 runtime]# docker start ba8dea7f1366 772b3eb707c1
Error response from daemon: oci runtime error: ID already in use, unique ID should be provided
Error response from daemon: oci runtime error: ID already in use, unique ID should be provided
Error: failed to start containers: ba8dea7f1366, 772b3eb707c1
[root@192 runtime]# 
[root@192 runtime]# docker ps
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS              PORTS                   NAMES
9ac96220087f        uhub.ucloud.cn/lxhtest1/ovs-plugin             "docker-ovs-plugin -d"   45 hours ago        Up About a minute                           lxh_plugin_1
b5c6f106eb1f        uhub.ucloud.cn/lxhtest1/openvswitch:2.3.2      "/usr/bin/supervisord"   45 hours ago        Up About a minute                           lxh_ovs_1
8425e4f99464        preugistry.service.ucloud.cn/cicd/deploy_log   "/bin/sh -c 'cron && "   45 hours ago        Up About a minute   0.0.0.0:1514->514/tcp   lxh_log_1
[root@192 runtime]#

**Comment by dlespiau** [comment]
This is a script to install clear containers on a one-shot CI machine (the environment is discarded after the CI run), so it doesn't have to be idempotent. That said we still need to have a better way for people to install the cc runtime from source (issue #157).

**Comment by egernst** [comment]
@wuzhy, can you please reopen if this is still an issue with the beta release?
