### ISSUE TITLE
create failing is not properly handled

### ISSUE THREAD

**Issue by dlespiau** [clearcontainers/runtime#176]
(updated to be actually correct, runc doesn't create a container if create fails)

Comparing runc with cc-runtime, when create fails we shouldn't leave the container behind. The spec is somewhat unclear on that: https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#create

with cc-runtime:

```
$ sudo cc-runtime create --console /dev/pts/9 --bundle /home/damien/clear/bundles/busybox foo2
fork/exec /usr/libexec/clear-containers/cc-shim: operation not permitted
$ echo $?
1
$ sudo cc-runtime list 
ID          PID         STATUS      BUNDLE                               CREATED                OWNER
foo2        0           ready       /home/damien/clear/bundles/busybox   0001-01-01T00:00:00Z   
```

with runc:

```
$ sudo docker-runc  create --console /dev/pts/9 --bundle /home/damien/clear/bundles/busybox foo
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"operation not permitted\""
$ echo $?
1
$ sudo docker-runc  list
ID          PID         STATUS      BUNDLE                               CREATED
```

**Comment by dlespiau** [comment]
To easily reproduce a failing `create`: 

```
$ sudo rm /var/lib/clear-containers/runtime/bundles/pause_bundle/bin/pause
```

**Comment by dlespiau** [comment]
Two more things to add there. When create is failing we also need to:

- not leave the qemu process behind
- free the proxy resources (if we've done a RegisterVM already)

Today:

```
# initial state, no qemu process
$  ps faux | grep qemu
root     22975  0.0  0.0 118520   996 pts/4    S+   12:32   0:00  |   |           \_ grep --color=auto qemu

$ sudo rm /var/lib/clear-containers/runtime/bundles/pause_bundle/bin/pause 

# the underlying create fails. The error message is already tracked in another issue
$ docker run --runtime cc busybox ls
docker: Error response from daemon: exit status 1: "exit status 1\n".

# argh!
[root@strange tests]# ps faux | grep qemu
root     23088 14.1  1.6 2684644 126472 ?      Sl   12:32   0:00   /usr/bin/qemu-lite-system-x86_64 ...
```

**Comment by grahamwhaley** [comment]
@MarioCarrilloA just fyi, I believe this is the same issue you were seeing when your system ran out of RAM resource, failed to create a container, and thus left a QEMU hanging around - I think...
Hmm, still, on second thoughts, if you were short on RAM resource then I believe it was probably the QEMU create that will have failed (QEMU would refuse to start due to lack of available memory to map) - so, maybe you have uncovered a different issue. Let's keep an eye on that, and log a new issue if we re-create and diagnose.

**Comment by egernst** [comment]
@jcvenegas  -- you get a chance to look @ this?

**Comment by jcvenegas** [comment]
@egernst  I did not, so I think the fix should be addressed in VirtContainers. If anything  at creation pod time fails,  will need to rollback by killing the VM and all the shims. @sboeuf does it make sense ?

**Comment by sboeuf** [comment]
@jcvenegas yes this has to be handled in virtcontainers.

**Comment by egernst** [comment]
Closing; tracked by https://github.com/containers/virtcontainers/issues/356
