### ISSUE TITLE
Remove the --debug

### ISSUE THREAD

**Issue by dlespiau** [clearcontainers/runtime#187]
Now that we can control logging from the config file, I don't believe we need this command line option.

**Comment by jodh-intel** [comment]
We might be able to remove `--debug`, but we cannot remove `--log` and `--log-format` as those are passed to the runtime by docker (if `runc` (well `docker-runc`) supports it, we need to too).

**Comment by dlespiau** [comment]
Edited the issue accordingly.

**Comment by jodh-intel** [comment]
Plan:

- [ ] Once https://github.com/containers/virtcontainers/pull/402 lands, re-vendor into the runtime.
- [ ] Add new `debug` options to the config file file the hypervisor, shim and runtime itself
- [ ] Remove the `--debug` flag so that all debug is controlled by the config file options.
