### ISSUE TITLE
Set VM parameters from a configuration file rather than hardcode

### ISSUE THREAD

**Issue by egernst** [clearcontainers/runtime#192]
Want to make sure that the same settings for number of slots, max memory and default memory for the VM is a parameter and not hardcoded in an equivalent to hypervisor.args.

This is a 3.0 equivalent to the following 2.1 issue: https://github.com/01org/cc-oci-runtime/issues/805

**Comment by dlespiau** [comment]
I think this is already covered by https://github.com/clearcontainers/runtime/issues/164. Closing. If you don't think that's the case, please to re-open.

**Comment by egernst** [comment]
That's fine, but I'll likely add more specific requirements on 164, then.
