### ISSUE TITLE
export loadConfiguration and implement SaveConfiguration

### ISSUE THREAD

**Issue by devimc** [clearcontainers/runtime#197]
the runtime is the only one that know how to manipulate its configuration hence in order to do not duplicate code and keep compatibility between projects loadConfiguration should be exported and SaveConfiguration should be implemented.
Tests should be able to generate runtime configuration files in order to use local($GOPATH) versions of cc-shim and cc-proxy

**Comment by sboeuf** [comment]
Could you elaborate why we need `LoadConfiguration()` and `SaveConfiguration()` from other projects ? Not sure to understand the final usage for that.
