### ISSUE TITLE
Modify Travis build to make use of docker

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#20]
_From @jodh-intel on September 29, 2016 9:32_

Travis is an excellent facility, but the fact that the newest environment they support is Ubuntu Trusty (14.04) is problematic given the old versions of tooling and libraries.

We should use Travis to trigger a build and test run inside a docker image since that way we can use any environment we wish (even multiple).

Related: #255, #295, #114, #155.

_Copied from original issue: 01org/cc-oci-runtime#305_

**Comment by sameo** [comment]
_From @jodh-intel on September 29, 2016 9:33_

Rework https://github.com/jodh-intel/cc-oci-runtime/blob/run-tests-in-travis-under-docker/ to only run unit tests (but including valgrind, cppcheck and code-coverage).

**Comment by egernst** [comment]
Before we hit the one year anniversary for activity on this issue, I think this is no longer relevant and should be closed. @sameo @jodh-intel , if you disagree let's open a new one.

**Comment by jodh-intel** [comment]
@erick0z - And we were *so* close to having :cake: and :balloon:'s and everything! :smile:
