### ISSUE TITLE
Autocompletion for Docker/CC commands, options, container ID doesn't work in CL 

### ISSUE THREAD

**Issue by bktan8** [clearcontainers/runtime#201]
In other distros, autocompletion for Docker commands, options, container ID works. But it doesn't work on CL. For example, in Ubuntu, if you start a container, Docker shows a very long container ID. You can simply stop it by issuing "docker stop" + the first couple of digits of the container ID, press <TAB>, and it will autocomplete. Doesn't do that on CL.

**Comment by dlespiau** [comment]
Hi,

What do you mean by CL? Clear Linux? This repository is about Clear Containers, we don't take issues with Clear Linux unfortunately.

**Comment by jcvenegas** [comment]
@bktan8  you can follow this in Clear Linux ML: dev@lists.clearlinux.org

**Comment by bktan8** [comment]
CL = Clear Linux.
