### ISSUE TITLE
Add "cc-check" command

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#204]
Add a `cc-check` sub-command that will perform the container-specific tests currently provided by [1].

We should not expect users to have to download and run a shell script from a different site to the one hosting the runtime: the runtime should provide the feature itself.

We could simply incorporate these checks into the runtime startup codepath. However, that seems inefficient since the runtime will be called multiple times but the tests only need to be run once (at most). As such, a separate command seems like the best approach initially.

---
[1] - https://download.clearlinux.org/current/clear-linux-check-config.sh

**Comment by dlespiau** [comment]
`cc-check` maybe?

**Comment by jodh-intel** [comment]
Yes, it looks ugly, but I guess we should "namespace" since `runc` doesn't provide this.
