### ISSUE TITLE
Installing from source "configuration.toml" is under /usr/local/etc/clear-containers/

### ISSUE THREAD

**Issue by gorozco1** [clearcontainers/runtime#206]
Runtime always looks in ``/etc/clear-containers/configuration.toml``. When installing from source without specify a different  --prefix is installed under /usr/local and runtime can't read configuration file. 

The user needs to manually create directory  ``/etc/clear-containers/`` and copy ``configuration.toml`` there.

**Comment by jodh-intel** [comment]
Now that #231 has landed, you can do what you need like this:

```
$ sudo make install SYSCONDIR=/etc
```

For the full list of variables to set to get expected paths:

- https://github.com/clearcontainers/tests/blob/master/.ci/install_runtime.sh#L26..L42

**Comment by jodh-intel** [comment]
Also, you can `make help` to see defaults or, say, `make help SYSCONFDIR=/foo/bar` to see how that might affect the build.

**Comment by gorozco1** [comment]
@jodh-intel what I was thinking is that if the user compiles by hand with `configure && make && make install` the binary is installed under `/usr/local/bin`  and the configuration is installed under /usr/local/etc/clear-containers/configuration.toml`.  And cc-runtime is still looking for the configuration under `/etc/` not under `/usr/local/etc` and I should expect because the user installed everything under the `/usr/local` hierarchy

**Comment by jodh-intel** [comment]
Hi @gorozco1 - I think #288 will handle the scenario you are describing.

**Comment by jodh-intel** [comment]
@gorozco1 - can we close this now?

**Comment by gorozco1** [comment]
yes we can close it.
