### ISSUE TITLE
Add a "cc-env" command

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#228]
It would be useful to have a `cc-env` command that shows information like:

- kernel being used.
- image being used.
- path to config file (maybe).

**Comment by dlespiau** [comment]
I would add:
 - config (either file and the configuration as understood by the runtime)
 - runtime, shim, proxy versions
 - OS distro and version
 - host kernel version
 - CPU
 - some of the dmidecode fields (maybe)
 - if we are running inside a VM

**Comment by jodh-intel** [comment]
That's a good list. And I totally agree that we need a simple way to collate all this information. But I'm wondering if this sort of info _might_ be better served by a helper shell script (although I appreciate that we've just merged #214, so maybe all of the above should also be "built-in"). I'll assume we're going for the built-in option for now though.

Regarding the proxy and shim versions, we really need the following to be actioned:

- https://github.com/clearcontainers/proxy/issues/69
- https://github.com/clearcontainers/shim/issues/32

**Comment by dlespiau** [comment]
The above should be somewhat straightforward to implement and not to burdensome  to carry around in the runtime. The main reason I see is avoiding extra steps for users to report the info we ask for.

**Comment by jodh-intel** [comment]
Yes, I'm sold: we need to make it trivial to gather the information we need the user to paste into an issue.
