### ISSUE TITLE
process.capabilities not implemented

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#24]
_From @jodh-intel on August 30, 2016 16:26_

See https://github.com/opencontainers/runtime-spec/blob/master/config.md#process-configuration.

_Copied from original issue: 01org/cc-oci-runtime#184_

**Comment by egernst** [comment]
Before we hit the one year anniversary for activity on this issue, I think this should be closed. @sameo please reopen if you disagree?

**Comment by sboeuf** [comment]
@egernst well this one has been implemented by @amshinde in both virtcontainers and agent, so I think it can be closed.

**Comment by egernst** [comment]
That's what I figured.  Too late anyway :)
