### ISSUE TITLE
support "create --console-socket ..." for docker 17.06

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#267]
See:

- https://github.com/01org/cc-oci-runtime/issues/1021
- https://github.com/opencontainers/runc/blob/master/create.go#L31.LL34

**Comment by sboeuf** [comment]
This is also needed by CRI-O tests. We will be able to enable more tests with this option supported.

**Comment by jodh-intel** [comment]
Superceded by #293.
