### ISSUE TITLE
document release process in wiki

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#301]
We need to document our release process in the wiki, as we do for CC 2.x:

- https://github.com/01org/cc-oci-runtime/wiki/Release-Process

**Comment by devimc** [comment]
https://github.com/clearcontainers/runtime/wiki/Release-Process
https://github.com/clearcontainers/runtime/wiki/Release-Checklist

can we close this one?

**Comment by jodh-intel** [comment]
Yep.
