### ISSUE TITLE
Enable and tune KSM

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#31]
### Problem Statement

All Clear Containers share the same kernel and guest OS image, and thus the hypervisor will allocate anonymous pages for both of those components. For many of them, those pages could be shared and deduplicated through the [Kernel Same Page Merging (KSM)](https://www.kernel.org/doc/Documentation/vm/ksm.txt) technology. Unfortunately, we are currently not taking full advantage of it for the following reasons:

1) Many distribution OSes do not enable KSM by default
2) Enabling KSM is only the first step. We need to also tune KSM to efficiently reduce our per-container memory consumption

### Solution

Both our runtime and proxy components can gather pieces of information about the current number of running/started/starting Clear Containers, the number of started containers during the last N seconds, etc...
By combining this data with at least the host available memory and CPU utilization, we should implement a ksm tuning loop that will:

1) Trigger KSM scans, depending on the number of started Clear Containers since the last scan and the number of already running containers.
2) Dynamically set the KSM scan period, depending on the system available memory, the CPU utilization and the rate of Clear Containers start (how many CC do we start per minute). We can even decide to disable periodic scanning (if possible) and control it fully.

#### Minimizing KSM impact
Running KSM frequently can have a significant impact on the overall system performance. We need to take advantage of KSM memory overhead reduction while at the same time minimizing the number of pages the KSM kernel thread wants and can scan:

- Enhance the KSM kernel interface to trigger it only on specific PIDs.
- Do not systematically marge all QEMU allocated pages as mergeable and be a little smarter about it.

cc @jtkukunas

**Comment by grahamwhaley** [comment]
@sameo is this now resolved with the cc-proxy auto KSM?

**Comment by grahamwhaley** [comment]
and with the even newer: https://github.com/kata-containers/ksm-throttler
I think we can close this.
