### ISSUE TITLE
Publish the Clear Containers PnP scripts

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#32]
So that one can easily reproduce and track PnP locally.

**Comment by sameo** [comment]
cc @jtkukunas

**Comment by dborquez** [comment]
PRs commited:
PR [#658](https://github.com/01org/cc-oci-runtime/pull/658) boot time scalability 
PR [#655](https://github.com/01org/cc-oci-runtime/pull/658) Memory footprint of a set of concurrent containers

**Comment by grahamwhaley** [comment]
Scripts can be found over at:
https://github.com/clearcontainers/tests/pull/225
