### ISSUE TITLE
Add more memory consumption benchmarks

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#34]
cc @jtkukunas

To be completed with more tests

#### Memory consumption exponential scaling
Does our memory consumption scale with the number of started containers ? With KSM enabled the average memory consumption per container should decrease with the number of containers.

We should measure the total average memory consumption per container for 1, 10, 100, 500 and 1000 running containers.

#### Memory density
We want to be able to measure Clear Containers memory density.
For a given machine (Available RAM, distro, etc...), we should measure how many Clear Containers can be started before we crash or before docker refuses to launch more.
This benchmark should be run with at least 2 parameters:
- How many containers do we launch at the same time (container batch) ?
- How long do we wait between each container batch ?

**Comment by grahamwhaley** [comment]
I've always also wanted to see the 'KSM burndown' graph - that is, how long does it take KSM to take effect and settle down to a steady number. That should be pretty easy to measure/generate.

**Comment by mcastelino** [comment]
This density test is a pure idle test. We should include a separate non idle test for memory intensive containers like an in-memory database.

**Comment by MarioCarrilloA** [comment]
@dborquez @sameo Done Average memory consumption per CC running 20 CC simultaneously, the footprint is the sum of the following components:

- PPS cc-proxy
- RSS cc-oci-runtime
- RSS cc-shim
- RSS qemu-lite

**Comment by dborquez** [comment]
- Completed:  Memory density test running in a plattform with 14GB of free memory
  - The average number of cc instances simultanously running is 114 for three repetitions

**Comment by grahamwhaley** [comment]
This was added with:
https://github.com/clearcontainers/tests/blob/master/metrics/density/footprint_data.sh
