### ISSUE TITLE
test with top 100 docker images

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#346]
See: https://github.com/01org/cc-oci-runtime/issues/425

**Comment by GabyCT** [comment]
I just ran the script “popular-containers-images.bats” on Ubuntu 16.10  on a Skylake NUC i5-6260U with the following specifications:
cc-runtime  : 3.0.0-alpha.4
OCI specs: 1.0.0-rc5
Docker version 17.06.0-ce, build 02c1d87

I had to do some modifications to the script for some images popular-containers-images.bats”  as some commands for some docker hub images were obsolete or not supported anymore. However, after the changes only two images were not able to run, one for the image of “couchdb” and the other one for the image “joomla” which are showing some errors while starting the image.

**Comment by GabyCT** [comment]
The modifications for the popular-containers-images.bats will be submitted later on the clearcontainers/tests repository and I will coordinate with @devimc to run this script on the Local CI.

**Comment by GabyCT** [comment]
should I close this issue and raised another one in clearcontainers/tests to submit the script?

**Comment by chavafg** [comment]
@GabyCT can you please test those 2 images with runc? So we know if something is wrong with our runtime. And also it would be great if you could post the errors here.

**Comment by GabyCT** [comment]
@chavafg I tried with runc version 1.0.0-rc3 and it is working. I verified the joomla image and it is working with CC3 , I just need it to change the test. However, the couchdb is not working

Here are the errors
1. docker run -ti -e COUCHDB_USER=test -e COUCHDB_PASSWORD=secretword couchdb
[WARN  tini (5)] Tini is not running as PID 1 and isn't registered as a child subreaper.
        Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
        To fix the problem, use -s or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
{error_logger,{{2017,7,26},{13,16,53}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{'EXIT',{function_clause,[{inet_config,set_hostname,[{error,enametoolong}],[{file,"inet_config.erl"},{line,240}]},{inet_config,init,0,[{file,"inet_config.erl"},{line,47}]},{inet_db,start_link,0,[{file,"inet_db.erl"},{line,112}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,314}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,297}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,263}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}},{offender,[{pid,undefined},{name,inet_db},{mfargs,{inet_db,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2017,7,26},{13,16,53}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,inet_db,{'EXIT',{function_clause,[{inet_config,set_hostname,[{error,enametoolong}],[{file,"inet_config.erl"},{line,240}]},{inet_config,init,0,[{file,"inet_config.erl"},{line,47}]},{inet_db,start_link,0,[{file,"inet_db.erl"},{line,112}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,314}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,297}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,263}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,27},{reductions,156}],[]]}
{error_logger,{{2017,7,26},{13,16,53}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,inet_db,{'EXIT',{function_clause,[{inet_config,set_hostname,[{error,enametoolong}],[{file,"inet_config.erl"},{line,240}]},{inet_config,init,0,[{file,"inet_config.erl"},{line,47}]},{inet_db,start_link,0,[{file,"inet_db.erl"},{line,112}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,314}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,297}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,263}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,inet_db,{'EXIT',{function_clause,[{inet_config,set_hostname,[{error,enametoolong}],[{file,\"inet_config.erl\"},{line,240}]},{inet_config,init,0,[{file,\"inet_config.erl\"},{line,47}]},{inet_db,start_link,0,[{file,\"inet_db.erl\"},{line,112}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,314}]},{supervisor,start_children,3,[{file,\"supervisor.erl\"},{line,297}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,263}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]}}}},{kernel,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,inet_db,{'EXIT',{function_clause,[{inet_config,set_hostname,[{error,enametoolong}]
