### ISSUE TITLE
Add more boot time benchmarks

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#35]
cc @jtkukunas

To be completed with more tests

#### Measure boot time scalability
On a given system running N containers, how does our boot time per container increase when starting a single container? N=[10, 50, 100]

**Comment by dlespiau** [comment]
So, we need to trace interesting events to measure the various boot phases across multiple processes: eg. runtime create() start, qemu exec, qemu/firmware boots the kernel, hyperstart starts, READY is sent, hyperstart createpod/startcontainer commands, runtime start() start and end, ...

I was thinking we use use either uprobes if we want to get fancy, or simple log traces the proxy can gather in one place. We'll have traces for debugging purposes anyway, so it seems the easier path to go for.

An interesting view would be something ala bootchard where we see the various processes (qemu, runtime create, runtime start, runtime stop) and how well we parallelize those processes: one thing that we want possible for 3.0, in the case of docker, is to hide the qemu/hyperstart boot latency behind docker sequencing the create and start commands. But, then, maybe the gains there would be small, we don't really know today.

**Comment by aduenasd** [comment]
The following tests were expanded to capture the request:
- Docker workload latency for 10, 50 and 100 containers
- Stress Kernel boot time for 10, 50 and 100 containers

**Comment by treeder** [comment]
Might be interesting to add shutdown time benchmarks too.

**Comment by grahamwhaley** [comment]
Just for ref, there is an Issue around the shutdown and rm times over here: https://github.com/clearcontainers/tests/issues/358

**Comment by grahamwhaley** [comment]
This was added with:
https://github.com/clearcontainers/tests/blob/master/metrics/time/launch_times.sh
