### ISSUE TITLE
Include memory consumption and boot time to our CI

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#36]
Gate runtime, @clearcontainers/proxy, @clearcontainers/shim PR merges by basic PnP runs: Container density and boot time for `docker run busybox true`.

cc @jtkukunas

**Comment by egernst** [comment]
@grahamwhaley  - can this be updated yet?

**Comment by grahamwhaley** [comment]
I'm going to say 'no' for the minute.
Although we have landed the code (tests and the script to invoke them), for instance here:
https://github.com/clearcontainers/tests/pull/349
and we are beta trialling the CI infra to execute and report on those, it is not stable and fully enabled yet. We'll close this down when it is up and running (and ideally after a short period of stability).
/cc @MarioCarrilloA

**Comment by MarioCarrilloA** [comment]
@egernst, well, at this moment, the metrics test about memory footprint is included in CI
https://github.com/clearcontainers/tests/blob/master/.ci/run_metrics_ci.sh
however I agree with the idea about to close this when we get stability

**Comment by grahamwhaley** [comment]
We are nearly there - we are just trying to tie the Jenkins machines back to github.
To note, we use a combination of these items:
https://github.com/clearcontainers/tests/blob/master/.ci/run_metrics_ci.sh
https://github.com/clearcontainers/tests/blob/master/.ci/jenkins_job_build.sh
https://github.com/clearcontainers/tests/tree/master/cmd/checkmetrics
