### ISSUE TITLE
docker attach gets frozen

### ISSUE THREAD

**Issue by GabyCT** [clearcontainers/runtime#363]
1. docker run -td --name test busybox sh
2. docker attach test
/# exit 13
exit
....
However, the container does not terminate, it is frozen.

This was tested with Ubuntu 16.10 with the following configuration
cc-runtime  : 3.0.0-alpha.4
OCI specs: 1.0.0-rc5
Docker version 17.06.0-ce, build 02c1d87

**Comment by egernst** [comment]
I see this issue as well.  versioning info and logs for runtime and proxy available @ https://paste.fedoraproject.org/paste/YulMGWGspIvPMIil6w7ZnQ

It isn't just that you fail on typing exit -- any commands after attaching fail.

**Comment by egernst** [comment]
note: if you start interactive and then detach (ctrl -p -q) and then attach, everything behaves as expected.  This appears to only occur when starting in daemon mode.

**Comment by amshinde** [comment]
To be able to interact with a container started in detach mode, it needs to be passed -i option. Without this the stdin is closed in detach mode and one is not able to interact with the container.
So, for the exit to work in the above case, the container would need to be started as
```
docker run -itd --name test busybox sh
```

(Note the -i option passed)
It would then be possible to interact with the container and send it commands after attaching to it.
This is the same case in 2.1.

To verify that the attach works without -i (stdout and stderr are attached), run a container such as 
```
docker run -td busybox top -b
```

An attach on the above container, would show the output from top command.
@egernst I think we can close this one.

**Comment by grahamwhaley** [comment]
note: @egernst https://paste.fedoraproject.org/paste/YulMGWGspIvPMIil6w7ZnQ and similar pastebin/paste type links are not great for referencing info on Issues here, as they rapidly expire, and we lose historical info which folks might later want to reference or use :-(
