### ISSUE TITLE
Add I/O benchmarks

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#38]
We should add I/O tests for measuring disk/volumes and filesystem throughput.
We know 9pfs is slow and we hope to be able to improve it over time, and thus we need to include benchmarks for it to our PnP suite.

cc @jtkukunas

**Comment by mcastelino** [comment]
The I/O benchmarks should comprehend both local volumes as well as remote volumes.
The remote volumes should be on a non oversubscribed storage network.
This will help establish if 9pfs will be bottleneck even for remote volumes mandating a better solution.

**Comment by grahamwhaley** [comment]
Assigning to @MarioCarrilloA This was mostly achieved in https://github.com/clearcontainers/tests/commit/6b924e8b6e2b4f28b604163ec55fd22a6d5824f5#diff-3ab4e1aa7a6a24302080e702d7031936, we now just need to enable in the 'run all' script once we are happy with the CI framework.

**Comment by grahamwhaley** [comment]
Also see #97

**Comment by grahamwhaley** [comment]
IO tests added, and new Issue opened to cover expansion of testing. See #97 for more details
