### ISSUE TITLE
unable to run with additional groups

### ISSUE THREAD

**Issue by GabyCT** [clearcontainers/runtime#387]
Using the following setup:
Ubuntu 16.10
cc-runtime : 3.0.0-alpha.4
OCI specs: 1.0.0-rc5
Docker version 17.06.0-ce, build 02c1d87

It is not possible to run a container run with additional groups
1. docker run --rm --group-add audio --group-add nogroup busybox id
uid=0(root) gid=0(root)

However, it should return
uid=0(root) gid=0(root) groups=10(wheel),29(audio),65534(nogroup)

**Comment by devimc** [comment]
https://github.com/containers/virtcontainers/pull/345 and https://github.com/clearcontainers/runtime/pull/437 fixed this issue

**Comment by sboeuf** [comment]
Yes everything has been merged but this is not fixed on latest release (not yet). We need to update the clear-xxxxx-containers.img with the latest agent changes.
@GabyCT do you have this test ready to be enabled in our CI ?

**Comment by GabyCT** [comment]
@sboeuf yes we already have the test https://github.com/clearcontainers/tests/blob/master/integration/docker/user_test.go, I will enable it

**Comment by sboeuf** [comment]
@GabyCT cool, thanks for confirmation. Wait for enabling this until we have a new packaging triggered for our clear-containers.img. I am waiting for a few patches to go into our agent before asking @jcvenegas and @gorozco1 to update this.

**Comment by GabyCT** [comment]
@sboeuf ok :)
