### ISSUE TITLE
Add networking benchmarks

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#39]
With Clear Containers we are pushing all network packets between the container and the host through a Linux bridge, with or without SRIOV.
Having basic networking benchmarks (iperf based ?) for Clear Containers with and without SRIOV would be needed.

cc @jtkukunas

**Comment by mcastelino** [comment]
The minimal networking benchmarks that we need to run (local bridge) as well as machine to machine are.
So we need to do each of these tests in both cases

- Test: Bandwidth Rate (using iperf)
We have a container that acts as a client and one as a server
```
iperf –c ${ip} –d –p ${port} –m –t 300
iperf –s –p ${port}
```
- Test: Jitter using iperf
```
iperf –c ${ip} –p {port} –u –m –t 300
iperf –s –u –p ${port}
```
- Test: Latency with ping
- Test: Latency with qperf (TCP and UDP)
```
qperf ${ip} udp_lat
qperf ${ip} tcp_bw tcp_lat
```
- Test: Differential CPU Consumption % vs Network Workload (Idle vs iperf max)
```
ps –no-headers –o %cpu –p ${qemu_pids}
```
- Test: Differential Memory consumption vs Network Load (Idle vs iperf max)
```
psstop | grep ${qemus_ids}
```
Both cases above, for a single server to client container with multiple connections
Number of connections should be chosen to match max bandwidth possible

- Memory Consumption % with Multiple Containers Network Workload (10 containers as a clients & 10 containers as a servers)
- CPU Consumption % with Multiple Containers Network Workload (10 containers as a clients & 10 containers as a servers)

The run to run variation in these tests will be fairly large. In the order of 10%.
So we need to check against relative performance vs runc for host networking.
For machine to machine tests however no regression beyond a few % points of prior observed maximum is acceptable.

**Comment by mcastelino** [comment]
@sameo With SRIOV we are doing a direct device pass through. So no bridge involved. This will be our highest performance mode for networking.

**Comment by egernst** [comment]
@mcastelino @GabyCT @grahamwhaley   -- are we running the networking PnP tests on 3.0 yet?

**Comment by grahamwhaley** [comment]
We have done a hand run, and @bwarden is in the process of adding the tests to the https://github.com/clearcontainers/tests/pull/162 repo right now.

**Comment by GabyCT** [comment]
@egernst , I think @grahamwhaley and @bwarden will work on that

**Comment by grahamwhaley** [comment]
Yep. See:
- https://github.com/clearcontainers/tests/issues/149
- https://github.com/clearcontainers/tests/issues/170
- https://github.com/clearcontainers/tests/pull/162

**Comment by egernst** [comment]
Next question is - -can we close this, then?

**Comment by grahamwhaley** [comment]
PR has not landed yet. Once we get that landed then sure this should close.

**Comment by grahamwhaley** [comment]
Assigning @bwarden 
We may not get the SRIOV tests in for the release, but the basic network tests that have started to merge should be.

**Comment by grahamwhaley** [comment]
PR landed: https://github.com/clearcontainers/tests/pull/321
I'll close this now.
If/when we get to SRIOV and the like then we can have new Issues.
