### ISSUE TITLE
Create an architecture document

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#392]
For parity with:

- https://github.com/01org/cc-oci-runtime/blob/master/documentation/architecture.md

**Comment by jodh-intel** [comment]
Hi @grahamwhaley - do you wanna take this one? ;)

**Comment by grahamwhaley** [comment]
heh, did I see that coming...? :-)  yes, that probably makes sense for me to take. I'll assign myself.... and everybody expect me to ask you annoying questions :-)

**Comment by jodh-intel** [comment]
Ah - I'd already opened #268 for this! ;-) Closing that one...

**Comment by jodh-intel** [comment]
Potentially related: https://github.com/clearcontainers/proxy/issues/104.

**Comment by egernst** [comment]
@grahamwhaley I wanted to check in on this -- I would like to contribute here if it helps.  Let me know if you have any existing .mds started and/or if there are areas I can grab.

**Comment by grahamwhaley** [comment]
Hi @egernst  I was going to start on this today.
My basic plan is to assess https://github.com/01org/cc-oci-runtime/blob/master/documentation/architecture.md and adopt/adapt as necessary.
I was thinking though - much of the architecture is really over in https://github.com/containers/virtcontainers, not in the runtime, as the runtime is a relatively thin shim. So, much of the documentation (detail at least) might be better placed over in https://github.com/containers/virtcontainers

Thus, I may tackle this slightly back to front - do the runtime arch docs that will reference virtcontainers, and then we can do a detailed virtcontainers doc afterwards.

**Comment by grahamwhaley** [comment]
@egernst fyi, I have done a first pass clone/clean of the cc-oci-runtime docs, which can be found on my branch here as WIP:
https://github.com/grahamwhaley/runtime/tree/20170823_arch_docs/docs/architecture

There are a couple of **fixme** items (clean up the hyperstart and qemu sections, ensure we have the correct networking ref/links etc.).

And then there are some more things I need or would like to do at least:
- fix any out of date diagram bits
- probably move the diagrams to SVG - we discussed that once before. I'll see how it goes (although I am normally a little frustrated at SVG tooling :-) )
- add some sort of 'design goal' and/or overview section at the top - it is a little 'dive right in' right now for my liking.
- I think we are missing a 'storage' section, so would like to add.

And then, before we push on further with this, I'd like to know if we agree the doc. would be heading in the right direction? I have an urge to re-arrange the order of it somewhat for instance (but can do that as a WIP/RFC after I have done the first major cleaning pass and even PR).

/cc @jodh-intel @mcastelino @sboeuf

**Comment by egernst** [comment]
@grahamwhaley  - I'll start taking a look at the diagram bits (which live on the [internal] google drive); will create a new folder setup so we differentiate 3.0 from 2.x....

**Comment by grahamwhaley** [comment]
sure thing @egernst One thing I know in the docs is to change all hyperstart refs to 'agent' at least.
And then I am envisioning some sort of architectural runtime diagram that will show how the runtime is built on top of virtcontainers.
I think we should use the already uploaded .odp file https://github.com/01org/cc-oci-runtime/blob/master/documentation/architecture-diagrams.odp (or the copy we place in this repo) as the master diagram document - or - if we move to svg, the .svg files themselves I expect will be their own masters.
Tell me if you think none of that makes sense.

**Comment by grahamwhaley** [comment]
Small update @egernst  I exported one of the diagrams to an .svg, made a modification using `inkscape` to ensure the load/edit/save cycle worked fine (preserving fonts, colours etc.), uploaded here https://github.com/grahamwhaley/runtime/blob/20170823_arch_docs/docs/architecture/overall-architecture.svg and modified the .md to use that instead of the .png.
All went OK, apart from it seems .svg inline pictures may not be supported by github md rendering. I'm going to look into that, and if we have to we'll have a build rule that converts the .svgs to .pngs as needed so at least we can formalise what tooling we are using.
Thus, I think storing the .svg files here as the master diagrams is feasible and the right way to go.
