### ISSUE TITLE
increase unit test coverage on exit.go

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#402]
Currently very low coverage.

See #93.

**Comment by jodh-intel** [comment]
Hi @amshinde - this is an easy one as the code in `exit.go` is only used by the tests. Hence, I'd move it to `main_test.go` and remove `exit.go` entirely.

**Comment by jodh-intel** [comment]
Hi @amshinde - any update on this?

**Comment by amshinde** [comment]
@sboeuf mentioned he will be taking a look at this. @sboeuf If you are, can you assign it to yourself?

**Comment by sboeuf** [comment]
@amshinde I am pretty busy with the CI right now and I have to write the tests for main.go. Not sure I will be able to handle this one. Maybe @devimc or @jcvenegas has some bandwidth to implement this one ?

**Comment by amshinde** [comment]
@sboeuf Ack. 
@jodh-intel I had a look at this earlier. The exit() function is used in main.go, so its not possible to move the exit function to main_test.go. I think the exit() function was added  to help run the go coverage tool by Damien. 
The only way I see to test the exit function is to have a forked process call exit(). But since a simple fork is not possible in golang, testing this function is tricky. Do you have any suggestions?

**Comment by jcvenegas** [comment]
@amshinde  is it possible to not call exit in this function and do it after call it , in main.go  ? or add anoter parameter to ask to not to exit ? (at least to verify the  all functions in the where called?

**Comment by jodh-intel** [comment]
@amshinde - ah! I'd missed that! ;)

In which case, how about this:

- modify `exit()` so that rather than calling `os.Exit(status)` it calls `exitFunc` where that is defined in `exit.go` as:
  ```
  var exitFunc func(int) = os.Exit
  ```
- create `exit_test.go`.
- create `init()` in `exit_test.go to set `exitFunc = testExitFunc` (that does not call `os.Exit()`).
- create some tests that call `exit()`:
  - when no calls to `atexit()` have been made.
  - when 1+ calls to `atexit()` have been made.

That will mean `exit()` works as expected from main, but we'll also get 100% coverage on `exit.go` I think.

**Comment by amshinde** [comment]
@jodh-intel Neat approach!  I will give it a go.
