### ISSUE TITLE
Define, document and publish reference workloads for our benchmarks

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#41]
We should define and publish a short set of custom workloads for our benchmarks.

#### Define
For example:

- A minimal workload: A busybox container that sleeps for one hour
- An I/O specific workload
- A networking workload

#### Document and publish
Each of those workloads should:

- Have their Dockerfile published here: https://github.com/clearcontainers/dockerfiles
- Be pushed to https://hub.docker.com/u/clearcontainers/
- Be the only used workloads in our benchmarking scripts

**Comment by grahamwhaley** [comment]
I think we can say this is effectively done by the directory and specifically the files at:
https://github.com/clearcontainers/tests/blob/master/metrics/run_all_metrics.sh
