### ISSUE TITLE
increase unit test coverage on config.go

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#413]
Currently very close to 100% (which looks to be achievable).

See #93.

**Comment by jodh-intel** [comment]
I think this just needs 1 more test similar to `TestConfigLoadConfigurationFailBrokenSymLink()` that creates a valid symlink to an unreadable file which will cause `loadConfiguration()` to fail.

**Comment by jodh-intel** [comment]
Hi @sboeuf - any update on this?

**Comment by sboeuf** [comment]
@jodh-intel this one is already all covered, isn't it ?

**Comment by jodh-intel** [comment]
Ah - I see what's happened - I raised this issue based on the coveralls output, but at that time coveralls was only running the tests as `root`. Now that #484 has landed, coveralls now gets to see the tests I actually wrote for `config.go` on #484 which increased the coverage to 100% when run as a non-root user! 

Closing as already done :smile:
