### ISSUE TITLE
Release 3.0.0-beta.1

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/runtime#417]
- [ ] Test the HEAD commit of the master branch using the tests included in the [tests repository][tests].
- [x] Update ```VERSION```.
- [ ] Generate OBS packages based on HEAD.
- [ ] Test OBS packages
	- [ ] Manual tests
		- [ ] Installation test.
		- [ ] Package signature test.
	- [ ] Automated tests
		- [ ] Integration tests included in the [tests repository][tests] under the integration directory.
- [ ] Tag release using new version.
- [ ] Write release notes:
  - [ ] Brief summary of known issues, pointing to the appropriate Issues/PRs.
  - [ ] Version of Docker (ideally range of versions, or "up to version X") supported by the release.
  - [ ] Version of the OCI spec (ideally range of versions, or "up to version X") supported by the release.
  - [ ] Version of Clear Container image used by the release.
  - [ ] Add links to Installation instructions.
  - [ ] Document any common vulnerabilities and exposures (CVEs) fixed with links to the CVE database.
- [ ] Post release details on the public mailing list.
- [ ] Update public IRC channel with a link to the latest release.

[tests]: https://github.com/clearcontainers/tests

**Comment by chavafg** [comment]
@jcvenegas I think item 1 is already covered by: https://semaphoreci.com/clearcontainers/runtime/branches/master/builds/169
