### ISSUE TITLE
Create the 3.0 release blog

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/runtime#425]
We will need do a blog announcing our 3.0 release, with highlighted new architecture, features and a subset of our release notes.

copied over from https://github.com/01org/cc-oci-runtime/issues/1055
Also need to assign: https://github.com/eadamsintel
but need to add him to the org first...

**Comment by grahamwhaley** [comment]
@eadamsintel added :-)

**Comment by jodh-intel** [comment]
How about putting a draft up on https://github.com/clearcontainers/runtime/wiki so we can all contribute?

**Comment by amyleeland** [comment]
Done- https://clearlinux.org/blogs/announcing-intel%C2%AE-clear-containers-30
