### ISSUE TITLE
version SHA for runtime doesn't update unless make clean

### ISSUE THREAD

**Issue by egernst** [clearcontainers/runtime#431]
after making a local commit during development, I expect the SHA associated with cc-runtime --version to be updated after doing a make.  This seems to only occur after doing a make clean first.  Note that the SHA exhibited during the build process doesn't match the resulting version given with cc-runtime --version:

```
eernst@eernst-nuc-2:~/go/src/github.com/clearcontainers/runtime$ ./cc-runtime --version
cc-runtime  : 3.0.0-beta.1
   commit   : 6ea23563d970c57f12c64f7ca40bbb817dfdca5d
   OCI specs: 1.0.0-rc5
eernst@eernst-nuc-2:~/go/src/github.com/clearcontainers/runtime$ git log -n1 --oneline
6ea2356 Revert "runtime: Switch to the new agent"
# Up until this point, all is well. Next, make a trivial change to update SHA:
#
eernst@eernst-nuc-2:~/go/src/github.com/clearcontainers/runtime$ git commit --amend -s
[master 3a0a091] Revert "runtime: Switch to the new agent"
 Date: Wed Aug 16 15:51:00 2017 -0700
 2 files changed, 1 insertion(+), 2 deletions(-)
eernst@eernst-nuc-2:~/go/src/github.com/clearcontainers/runtime$ git log -n1 --oneline
3a0a091 Revert "runtime: Switch to the new agent"
eernst@eernst-nuc-2:~/go/src/github.com/clearcontainers/runtime$ make
cc-runtime - version 3.0.0-beta.1 (commit 3a0a091f3777411c1262cf69e755ad800b895188)

• Summary:

        Clear Containers system build     : no

        binary install path (DESTTARGET)  : /usr/local/bin/cc-runtime
        config install path (DESTCONFIG)  : /usr/local/etc/clear-containers/configuration.toml
        hypervisor path (QEMUPATH)        : /usr/local/bin/qemu-lite-system-x86_64
        assets path (PKGDATADIR)          : /usr/local/share/clear-containers
        proxy+shim path (PKGLIBEXECDIR)   : /usr/local/libexec/clear-containers
        pause bundle path (PAUSEROOTPATH) : /usr/local/var/lib/clear-containers/runtime/bundles/pause_bundle
#Note build output above matches what is expected for source SHA, while version
# provided below is the prior HEAD
#
eernst@eernst-nuc-2:~/go/src/github.com/clearcontainers/runtime$ ./cc-runtime --version
cc-runtime  : 3.0.0-beta.1
   commit   : 6ea23563d970c57f12c64f7ca40bbb817dfdca5d
   OCI specs: 1.0.0-rc5
eernst@eernst-nuc-2:~/go/src/github.com/clearcontainers/runtime$ make clean
     CLEAN   clean
     CLEAN   clean
eernst@eernst-nuc-2:~/go/src/github.com/clearcontainers/runtime$ make
     GENERATE config-generated.go
cc-runtime - version 3.0.0-beta.1 (commit 3a0a091f3777411c1262cf69e755ad800b895188)

• Summary:

        Clear Containers system build     : no

        binary install path (DESTTARGET)  : /usr/local/bin/cc-runtime
        config install path (DESTCONFIG)  : /usr/local/etc/clear-containers/configuration.toml
        hypervisor path (QEMUPATH)        : /usr/local/bin/qemu-lite-system-x86_64
        assets path (PKGDATADIR)          : /usr/local/share/clear-containers
        proxy+shim path (PKGLIBEXECDIR)   : /usr/local/libexec/clear-containers
        pause bundle path (PAUSEROOTPATH) : /usr/local/var/lib/clear-containers/runtime/bundles/pause_bundle

     BUILD   cc-runtime
     CONFIG  config/configuration.toml
cc -Os -Wall -Wextra -static   -c -o pause/pause.o pause/pause.c
     BUILD   pause
eernst@eernst-nuc-2:~/go/src/github.com/clearcontainers/runtime$ ./cc-runtime --version
cc-runtime  : 3.0.0-beta.1
   commit   : 3a0a091f3777411c1262cf69e755ad800b895188
   OCI specs: 1.0.0-rc5
```

**Comment by dvoytik** [comment]
This could be solved by a local git hook. I can submit a PR for this issue.

**Comment by grahamwhaley** [comment]
A git hook could do it. Alternatively (and I'm not too proud of this), I wonder if you can make the .git dir a dep. of the generated files. OK, that will rebuild the generated files for any change in the .git dir, but it would be 'less hidden' (would be visible in the Makefile) than a git hook maybe (buried in the .git dir somewhere).

**Comment by jodh-intel** [comment]
Rebuilding `config-generated.go` every time wfm as it's tiny and the name really implies it should be rebuilt every time anyway ;)

**Comment by grahamwhaley** [comment]
@jodh-intel do you mean rebuild on every make no matter what, or tie it to any changes in .git subdir? Just checking like. The rebuild every time might annoy me :-) - in projects past when they had that I'd spend some cycles staring at a Make that did not do nothing, wondering what on earth I'd changed ;-)

**Comment by jodh-intel** [comment]
sorry, yes, rebuilding every time due to that config file being recreated every time would be a pita. The trouble with the `.git/` dir hack is that... there might not be one! If you download a release source archive, it won't be there.

Which reminds me, we should really be doing something like:

- https://github.com/01org/cc-oci-runtime/pull/213

**Comment by dvoytik** [comment]
My idea was to create 'install git-hooks' target which installs hooks scripts (creates softlinks in .git/hooks/). Each time user runs 'git checkout' or 'git commit' the hooks will update _.git_head_ file in the root directory. Then config-generated.go must be set up to depend on _.git_head_. If _.git_head_ is absent then Makefile can generate it (in case when .git is absent).

**Comment by grahamwhaley** [comment]
just to note, I expect we can work around the non-existence of a .git dir with some make wildcard and conditionals, if we did go that route.

@dvoytik - if you made the 'install git-hooks' rule depend on the hooks being there - that is, if they auto-installed the first time make was run, that would in some ways feel better to me as folks would not forget to install them. /me suspects you were thinking that already maybe.
Of course, the auto-installing also makes me squirm a bit, but probably the better of two evils.

I'm going to say.... @jodh-intel @sboeuf if you have a preference for one of these options, shout, and we'll go that route. I'm happy either way.

**Comment by dvoytik** [comment]
@grahamwhaley, I was thinking about auto-installation also. If doesn't brake CI then I'm simply +1

**Comment by dvoytik** [comment]
I decided to make the patch simpler and just remove config-generated.go in the git hook scripts. Let me know if I should rework it differently. Thanks.
