### ISSUE TITLE
cc-check should only warn if "unrestricted_guest" is not set when running under a hypervisor

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#439]
Now that virtcontainers provides a way to detect if running under a hypervisor...

- https://github.com/containers/virtcontainers/pull/343

... we need to update `cc-check` to determine more intelligently if the environment is capable of running a Clear Container since although environments like Azure do not provide `unrestricted_guest`, it *is* still possible to run a Clear Container on it.

In summary, `cc-check` needs to do the following:

- if running under a hypervisor, only warn if `unrestricted_guest` is not set (since it does work under Azure for example).
- If not running under a hypervisor, error if `unrestricted_guest` is not set (no change to current behaviour).

See comments on https://github.com/clearcontainers/runtime/pull/422.

**Comment by sboeuf** [comment]
:+1:
