### ISSUE TITLE
Need CentOS installation guide

### ISSUE THREAD

**Issue by jovizhangwei** [clearcontainers/runtime#474]
There don't have CentOS installation guide in below link.

https://github.com/clearcontainers/runtime/blob/14d8084822980341ee9cc656eb4b42d7991a0fb6/docs/developers-clear-containers-install.md

**Comment by jodh-intel** [comment]
Hi @jovizhangwei - thanks for raising. This is actually an in-progress PR: #372.

**Comment by jodh-intel** [comment]
Closing as this is tracked on the PR and its issue...
