### ISSUE TITLE
Annotations are not exposed to the Clear Container

### ISSUE THREAD

**Issue by devimc** [clearcontainers/runtime#49]
_From @jodh-intel on Jul 18, 2016_

See https://github.com/opencontainers/runtime-spec/blob/master/config.md#annotations.

_Copied from original issue: 01org/cc-oci-runtime#21_

**Comment by devimc** [comment]
_From @grahamwhaley commented on Jul 29, 2016_

More a bug than an enhancement or feature, as we have missing functionality. May need to raise priority depending on feature demands.

**Comment by devimc** [comment]
_From @amshinde on Jul 29, 2016_

I am not clear how annotations are going to be used by the container. A quick search through runc, shows that they are simply stored and read bacc from the state file.

**Comment by devimc** [comment]
_From @jodh-intel on Aug 30, 2016_

The spec is not clear on how this data should be made available to the container so it would be interesting to see what runc does with it.

**Comment by dlespiau** [comment]
We expose annotations in the container state, virtcontainer uses them. I think we can close this one. Do re-open if you think otherwise.
