### ISSUE TITLE
cannot install latest packages on ubuntu (ciao-down)

### ISSUE THREAD

**Issue by egernst** [clearcontainers/runtime#540]
cc-runtime fails to install, sighting that I have held broken packages. Details:

$> sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/xUbuntu_$(lsb_release -rs)/ /' >> /etc/apt/sources.list.d/clear-containers.list"
$> curl -fsSL http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/xUbuntu_$(lsb_release -rs)/Release.key | sudo apt-key add -
$> sudo -E apt-get update
$> sudo -E apt-get install -y cc-runtime cc-proxy cc-shim
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cc-runtime : Depends: qemu-lite (>= 2.7.1+git.741f430a96-6.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

$>  apt-cache depends cc-runtime
cc-runtime
  Depends: libc6
  Depends: cc-runtime-bin
  Depends: cc-runtime-config
  Depends: qemu-lite
  Depends: clear-containers-image
  Depends: linux-container
  Depends: cc-proxy
  Depends: cc-shim
  Conflicts: <cc-oci-runtime>
  Replaces: <cc-oci-runtime>
    cc-runtime

**Comment by egernst** [comment]
@jodh-intel @gorozco1

**Comment by egernst** [comment]
Manually installing qemu-lite does't resolve this.  The installed version shows 2.7.0, and doesn't show a SHA either:

eernst@singlevm:~$ sudo -E apt-get install -y qemu-lite 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  qemu-lite
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/4,426 kB of archives.
After this operation, 18.3 MB of additional disk space will be used.
Selecting previously unselected package qemu-lite.
(Reading database ... 91575 files and directories currently installed.)
Preparing to unpack .../qemu-lite_2.7.1+git.741f430a96-0+7.1_amd64.deb ...
Unpacking qemu-lite (2.7.1+git.741f430a96-0+7.1) ...
Setting up qemu-lite (2.7.1+git.741f430a96-0+7.1) ...

eernst@singlevm:~$ /usr/bin/qemu-lite-system-x86_64 --version
QEMU emulator version 2.7.0, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers

**Comment by gorozco1** [comment]
This will be tracked and fixing in `packaging` repo https://github.com/clearcontainers/packaging/issues/98

**Comment by gorozco1** [comment]
Fixed with https://github.com/clearcontainers/packaging/pull/102
