### ISSUE TITLE
Add stateless support 

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/runtime#551]
cc-runtime should provide at least two paths to read its configuration path. 

- default config  directory: this path is for default system configuration (managed by the linux distribution)  
By default this path could be:
`/usr/share/defaults/clear-containers/`

- sysconf directory: Path to override default configuration ( used by the system administrator)
By default this path could be:
`/etc/clear-containers/`

**Comment by jcvenegas** [comment]
More information about stateless: https://clearlinux.org/features/stateless

**Comment by egernst** [comment]
needed for https://github.com/clearcontainers/packaging/issues/105

**Comment by jodh-intel** [comment]
I have no idea why github thinks I removed the release-gating label - re-added.
