### ISSUE TITLE
We should consider disabling any debug information while building the runtime.

### ISSUE THREAD

**Issue by amshinde** [clearcontainers/runtime#572]
As per this link : https://golang.org/doc/gdb, on compiling and  linking Go programs with the gc toolchain on Linux, the resulting binaries contain DWARFv3 debugging information.
While it may make sense to to have this for tests, we should consider disabling this otherwise.

Linker flags that I see for disabling debug info (https://golang.org/cmd/link/):
-s  Omit the symbol table and debug information.
-w Omit the DWARF symbol table.

This would also help decrease the binary size due to stripped off symbols.

**Comment by amshinde** [comment]
@sameo What do you think?

**Comment by grahamwhaley** [comment]
Just a note - it might be that the binaries already get stripped when we are generating the image/installers (OBS etc.) - that is quite a common thing to happen in packaging - /cc @gorozco1 for reference.
For developing we probably want to leave the symbols around - so maybe we need to add the strip/flags into the runtime where it decides if you are doing a 'release build' or not etc.

**Comment by amshinde** [comment]
@grahamwhaley I checked and did find that OBS strips the binaries. I'll close this one.
