### ISSUE TITLE
docker: Error response from daemon: exit status 1: "ERROR received from Hyperstart\n".

### ISSUE THREAD

**Issue by piersharding** [clearcontainers/runtime#588]
Hi -
I'm having a problem with trying to install and launch a basic container.  I have followed the instructions for 3.0 from here https://github.com/clearcontainers/runtime/blob/master/docs/ubuntu-installation-guide.md.
I am running Ubuntu 17.04 with Docker Version: 17.06.2-ce, and cc-runtime  : 3.0.0-beta.2.

When launching a test container with: 
```
docker run -ti --runtime=cor alpine bash
```
I receive:
```
docker: Error response from daemon: exit status 1: "ERROR received from Hyperstart\n".
```

I have enabled debugging and logging with:
```
 cc-runtime --debug --log=/tmp/cc.log
```
 and see a line like this:
```
time="2017-09-20T13:58:31+12:00" level=info msg="Hyperstart config &{/run/virtcontainers/pods/3904125aabdc734fe9aea210501f884e1cc546f6e8134e6bb81c0d4b48ee1229/hyper.sock /run/virtcontainers/pods/3904125aabdc734fe9aea210501f884e1cc546f6e8134e6bb81c0d4b48ee1229/tty.sock [] [{channel0 charch0 /run/virtcontainers/pods/3904125aabdc734fe9aea210501f884e1cc546f6e8134e6bb81c0d4b48ee1229/hyper.sock sh.hyper.channel.0} {channel1 charch1 /run/virtcontainers/pods/3904125aabdc734fe9aea210501f884e1cc546f6e8134e6bb81c0d4b48ee1229/tty.sock sh.hyper.channel.1}] /var/lib/clear-containers/runtime/bundles/pause_bundle/bin/pause}"
time="2017-09-20T13:58:31+12:00" level=error msg="open /run/docker/libcontainerd/3904125aabdc734fe9aea210501f884e1cc546f6e8134e6bb81c0d4b48ee1229/config.json: no such file or directory"
```

Any ideas what the problem might be?

Thanks,
Piers Harding.

**Comment by MarioCarrilloA** [comment]
Hi @piersharding , it is possible that alpine image does not have `bash` available, could you please try this:

`docker run -ti --runtime=cor alpine sh`

**Comment by piersharding** [comment]
Ha - fantastic!  That was all the problem was - never occurred to me that bash wouldn't exist :-(.

Thanks very much for having a look.

Cheers,
Piers.
