### ISSUE TITLE
Unify versions.txt

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/runtime#608]
There is a different places to try to control dependencies need by Clear Containers 3.0

https://github.com/clearcontainers/runtime/blob/master/versions.txt
https://github.com/clearcontainers/runtime/blob/master/versions.txt
https://github.com/clearcontainers/packaging/blob/master/versions.txt

We have to remove duplicated dependencies or try to centralize only in one place.

**Comment by jcvenegas** [comment]
@jodh-intel yep! versions everywhere :P

**Comment by jcvenegas** [comment]
@jodh-intel @gorozco1 @sameo now the question is where this things should live? IMO it should be the runtime it is the one that uses the rest of the components .

**Comment by jodh-intel** [comment]
I agree this isn't ideal. It would be nice to keep everything in "runtime", but the "tests" repo needs some of these details, but "runtime" needs "tests" for CI (circular dependency).

Maybe we need a new https://github.com/clearcontainers/dependencies repo that all the other components could pull? :smile:
