### ISSUE TITLE
cri-o tests fail randomly

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#622]
Occasionally, the `ctr execsync` cri-o test fails:

```
++ time bats --tap crio.bats
1..16
ok 1 ctr not found correct error message
ok 2 ctr termination reason Completed
ok 3 ctr termination reason Error
ok 4 ctr remove
ok 5 ctr lifecycle
ok 6 ctr logging
ok 7 ctr logging [tty=true]
ok 8 ctr list filtering
ok 9 ctr list label filtering
ok 10 ctr metadata in list & status
ok 11 ctr execsync conflicting with conmon flags parsing
ok 12 ctr execsync
ok 13 ctr device add
not ok 14 ctr execsync failure
# (in test file crio.bats, line 546)
#   `[ "$status" -eq 0 ]' failed
```
(for example http://cc-jenkins-ci.westus2.cloudapp.azure.com/job/clear-containers-runtime-azure-ubuntu-16-04/178/consoleText)

Related: https://github.com/clearcontainers/runtime/issues/521

**Comment by jodh-intel** [comment]
@grahamwhaley, @sameo, @sboeuf - I think this may be edging towards a P1 due to the impact this is having on our PRs. Thoughts?

@sboeuf - did I hear you say you were planning to look at crio this week... ? :)

**Comment by grahamwhaley** [comment]
It would sure be nice to fix it. Do we have any ideas at all what makes it happen?

**Comment by jodh-intel** [comment]
I have zero idea. @sboeuf ?

**Comment by sboeuf** [comment]
@jodh-intel I have no idea right now either, but yes I would like to see those sporadic issues go away. This is a P1 IMO.

**Comment by jodh-intel** [comment]
Hi @sboeuf - Assigning to you since presumably this is part of #676 (?)

**Comment by sboeuf** [comment]
yeah sure no problem, we have a fix for that ;)
