### ISSUE TITLE
Unbreak gofmt

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#624]
The `gofmt` logic in `.ci/go-static-checks.go` is incorrect.

**Comment by grahamwhaley** [comment]
Is that the old 'inverted check' debate - should we have it hard define what it should or should not check ??

I'll note, I'm sure I have an open issue to 'fix', that is more like unify, the static checkers across all the repos, ideally having a single static checker script, probably in the tests/.ci repo dir, that is then used for all the repos - one script to rule them all. I'm not expecting you to try and do that whilst fixing this though, but thought I'd mention it for good measure...

**Comment by jodh-intel** [comment]
I think the approach of this script is pragmatic for the time being: slurp all go code excluding code under vendor and `.git/`. That's obviously the maximal approach and if it starts to somehow check "too much" and then falls over, we'll be notified so we can tweak the config. But better that than not checking enough I'd say.

/me looks forward to @grahamwhaley's `static-checker-script-to-rule-them-all.sh` :smile:
