### ISSUE TITLE
Change logfile format to encode timezone as an offset

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#650]
The logfile timestamps currently include a timezone identifier (like `BST`) but we should encode as an offset (`+01:00`) for consistency with the proxy.

Ref: https://github.com/clearcontainers/proxy/pull/136.

**Comment by grahamwhaley** [comment]
What would you think to dropping the TZ completely, and always reporting in UTC? It would make everything a touch smaller and easier to read imo

**Comment by jodh-intel** [comment]
That's rather more difficult as the standard golang time format don't offer that option. This issue is to make everything "self-consistent" so all components log in the same format. Although we might not care about the TZ, others might and by having it as an offset, it's easier to manipulate.

**Comment by jodh-intel** [comment]
Oh - also worth mentioning that when we have the log parser tool (https://github.com/clearcontainers/tests/issues/578), we could always add an option to strip the TZ.

**Comment by grahamwhaley** [comment]
Strip, or adjust to UTC :-)
