### ISSUE TITLE
Install Instructions are Wrong

### ISSUE THREAD

**Issue by vikalyan** [clearcontainers/runtime#724]
# Description of problem

I have been following the instructions here for install Clear Containers 3.0 in a Ubuntu 16.04 host:

https://github.com/clearcontainers/runtime/blob/master/docs/ubuntu-installation-guide.md

When attempting to retrieve the GPG key as specified, the install sequence failed with a HTTP 404 - Not Found error. If I browse the directories on the server, it looks like the key files referenced in the instructions have been removed. This update was made on Oct 13, 2017.

In addition, the repository itself has no information.

# Expected result

Install should work according to the docs.

# Actual result

Unable to install clear containers by following the docs.

**Comment by vikalyan** [comment]
The CC binary packages are on longer available on download.opensuse.org. As far as I can see, this means nobody can install cc.

**Comment by vikalyan** [comment]
The issue appears to be resolved now and the packages are available. However, it is interesting that for nearly 48 hours none of the packages were available. Does the build process delete existing packages in the repository before uploading on a successful build?

**Comment by jodh-intel** [comment]
Hi @vikalyan - thanks for reporting this.

@gorozco1, @erick0z - can you provide any details here?

**Comment by gorozco1** [comment]
This was a problem with [OBS](https://build.opensuse.org/) being down for 48hrs due p[lanned maintenance. ](https://news.opensuse.org/2017/10/04/planned-downtime-to-affect-opensuse-services/).

**Comment by jodh-intel** [comment]
Thanks @gorozco1.

@vikalyan - I'll close this for now as OBS is out of our control.

**Comment by vikalyan** [comment]
@jodh-intel @gorozco1 Thank you! No problem with closing the issue. Just concerned that OBS being down implies that package feeds are offline as well.

**Comment by gorozco1** [comment]
@vikalyan We are working on fixing that
