### ISSUE TITLE
Update Ubuntu install guide for 16.10 and 17.04 (and 17.10 tomorrow!)

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#732]
The [Ubuntu install guide](/clearcontainers/runtime/blob/master/docs/ubuntu-installation-guide.md) needs to be tested on Ubuntu 16.10, 17.04 and (as of 19 October) 17.10), and the text updated to state it supports these releases.

(For 17.10 we'll need @gorozco1's help to update OBS).

Related #731.

**Comment by erick0z** [comment]
As soon as the repository is available in OBS, a new build can be triggered for 17.10.

**Comment by GabyCT** [comment]
working properly with 16.10

**Comment by GabyCT** [comment]
There is an issue with 17.04 when I am doing the following
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
curl: (35) Unknown SSL protocol error in connection to ...
gpg: no valid OpenPGP data found.

**Comment by GabyCT** [comment]
I will replace the curl for other thing

**Comment by GabyCT** [comment]
Instead of 
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
I will use
$ wget -qO - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

I will update the guide as soon as the OBS packages are for 17.10
