### ISSUE TITLE
Drop the global logger and switch to syslog/journald

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/runtime#788]
The runtime has a [global logfile](https://github.com/clearcontainers/runtime#global-logfile). This concept was added in the early days of Clear Containers as it was useful to have a persistent log of all container activity. This was particularly important for containers that fail since, under Docker, if a container fails to be created, Docker will delete all trace of the container which made debugging tricky ;)

At the time of its introduction, the system had fewer components, but now we have the shim and the proxy (and the agent indirectly) logging to syslog/journald, it makes sense to be consistent and log everything to the same place.

By dropping the global logfile feature and making the runtime use syslog/journald instead, we get all the obvious benefits of using the system log facility (like making life easier for admins, remote logging, etc).

@sameo, @grahamwhaley, @sboeuf, @mcastelino - what's your vote?

**Comment by grahamwhaley** [comment]
That sounds notionally correct to me - if all other parts are using syslog/journald and the runtime is the odd one out, then let's move it over.
Can anybody think of any downsides or reasons not to?

**Comment by sboeuf** [comment]
@jodh-intel this makes sense to me, and it's gonna be easier to track the sequencing of what happened between all the components. +1
