### ISSUE TITLE
run with macvlan failed

### ISSUE THREAD

**Issue by gogolxdong** [clearcontainers/runtime#847]
docker network create -d macvlan --subnet 192.168.4.0/24 --gateway 192.168.4.1 -o parent=eth0 vlan4
docker run -it --net=vlan4 centos:latest
ocker: Error response from daemon: OCI runtime create failed: Could not get veth interface: eth0: Incorrect link type macvlan, expecting veth: unknown.

**Comment by jodh-intel** [comment]
Hi @gogolxdong - please could you:

- Enable full debug:
  ```
  $ sudo sed -i -e 's/^#\(enable_debug\).*=.*$/\1 = true/g' /usr/share/defaults/clear-containers/configuration.toml
  ```
- Re-run the `docker` command.
- Paste the output of `sudo cc-collect-data.sh` into this issue (after reviewing it to make sure it doesn't contain any confidential/private details).

**Comment by egernst** [comment]
@gogolxdong -- thanks for opening the issue -- i can reproduce it locally and will look into this today.

**Comment by jodh-intel** [comment]
Thanks @gogolxdong - once we've got a handle on this and fixed it, can we create a test either in this repo or https://github.com/clearcontainers/tests I wonder to avoid a regression?

**Comment by egernst** [comment]
Yes.  That was my first step on this -- see if we had that in our CI yet.  Will open an issue for that now.

**Comment by mcastelino** [comment]
@gogolxdong this is a limitation of the current implementation. I have a PR pending to add support for macvlan. Once this merges we will have macvlan support.

https://github.com/containers/virtcontainers/pull/447
