### ISSUE TITLE
clearcontainers vs clear-containers in paths

### ISSUE THREAD

**Issue by dlespiau** [clearcontainers/runtime#85]
We currently use both, sometimes it's `/var/run/clearcontainers` and other times `/var/lib/clear-containers`. Pick one and stick with it. A quick git grep suggest we like `clear-containers` better.

**Comment by jodh-intel** [comment]
+1 for `clear-containers` as the final element as it's easier to read.

**Comment by dlespiau** [comment]
The tag was missing from the commit :( closing by hand.
