### ISSUE TITLE
Downgrade CC image.

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/runtime#889]
# Description of problem

As https://github.com/clearcontainers/agent/issues/182 is still not fully solved, we need to downgrade the CC image to 19350, which works well with kubernetes.

**Comment by sboeuf** [comment]
@chavafg you mention this is not fully solved, but could you provide the new logs for this. I would like to make sure we have the exact same issue.
Also, could you provide the steps to reproduce this issue ? It's not clear to me what we're doing to reach this issue.
