### ISSUE TITLE
Is there only one cc-proxy instance running per Clear Containers host?

### ISSUE THREAD

**Issue by miaoyq** [clearcontainers/runtime#908]
I get the follow description about cc-pproxy in [architecture.md](https://github.com/clearcontainers/runtime/blob/master/docs/architecture/architecture.md)
```
The Clear Containers proxy (cc-proxy) multiplexes and demultiplexes those commands and streams for all container virtual machines. There is only one cc-proxy instance running per Clear Containers host.
```

But I found that each container has a corresponding `cc-proxy` process when I create two containers by docker+cc on my host.  Have anything error in my env? 

![image](https://user-images.githubusercontent.com/17755856/34706834-e52010d0-f544-11e7-984e-de921a4b65ec.png)

Expect to get help, thanks!

**Comment by jodh-intel** [comment]
Hi @miaoyq - good catch. Yes, the architecture changed when #835 landed so that there is now one proxy started for each virtual machine. However, the architecture document clearly wasn't updated to reflect this change.

I'll fix the document...

Related: #795.

**Comment by miaoyq** [comment]
@jodh-intel  Got it, Thanks for explanation :)
