### ISSUE TITLE
docs: sriov: how to use lspci to see if NIC supports SR-IOV

### ISSUE THREAD

**Issue by grahamwhaley** [clearcontainers/runtime#917]
# Description of problem

Our SR-IOV doc does not detail many ways on how to check if your NIC hardware actually supports SR-IOV.
You can check that using `lspci`, so add that to the doc.

**Comment by jodh-intel** [comment]
Just an idea, but we *could* [*] update the collect script to include those details. The doc could then just get the users to run the script:

- https://github.com/clearcontainers/runtime/blob/master/data/cc-collect-data.sh.in

---
[*] - in fact probably should to make debuging SR-IOV issues easier.

**Comment by grahamwhaley** [comment]
I agree I think we should add that info to the collect script. I'm not sure we need to add use of the collect script to the SR-IOV docs - as they are an install guide rather than a debug guide. Let me at least open an issue for the collect script extension request...

**Comment by egernst** [comment]
agreed.  Augmenting the collection script is good, but I think the update you make in #918 is helpful/educational.
