### ISSUE TITLE
makefile: Allow for kata build

### ISSUE THREAD

**Issue by sboeuf** [clearcontainers/runtime#919]
I think we should add the possibility to generate everything for a `kata-runtime` binary from the Makefile. We would use `make kata` in order to generate everything we need.

**Comment by jodh-intel** [comment]
Related: #920, #921.

**Comment by jodh-intel** [comment]
I agree in principle, but it should probably be as follows for consistency with what we have already:

```
# build for Clear Containers (already exists)
make build-cc-system  && sudo make install-cc-system

# build for Kata Containers (TODO :)
make build-kata-system  && sudo make install-kata-system

```

**Comment by sboeuf** [comment]
@jodh-intel I agree, but I didn't want to introduce too much changes for our current CC case. But for consistency, not using only `make` for CC would be better.
