### ISSUE TITLE
Improve runtime unit tests code coverage

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#93]
Runtime's unit testing only covers 35% of the runtime code today.
The code will need some refactoring but this needs to be improved.

**Comment by jodh-intel** [comment]
This is becoming a placeholder for sub-tasks. See:

- #359 
- #262 
- #191

**Comment by jodh-intel** [comment]
This issue can be used primarily to add the basic mock testing framework which will enable the other files in the runtime to have full unit tests created.

**Comment by jodh-intel** [comment]
See #394, #395, #396, #397, #398, #399, #400, #401, #402, #403, #404, #405, #406.

**Comment by jodh-intel** [comment]
Overall unit-test coverage on the runtime is now 97% as shown by Coveralls:

- https://coveralls.io/github/clearcontainers/runtime

We have plans to improve how we track changing unit-test figures, but I think we can consider the task on this issue complete.
