### ISSUE TITLE
Missing virtcontainers OCI packages logs

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#934]
### Description of problem

When debugging the OCI package, we do not get the package logs from the runtime.

**Comment by jodh-intel** [comment]
This looks to be a two-part bug - the runtime isn't calling OCI's `SetLogger()`, but that function isn't adding an "oci" field.

**Comment by jodh-intel** [comment]
@sameo - shouldn't...

- https://github.com/containers/virtcontainers/blob/master/pkg/oci/utils.go#L106..L108

be doing the same as:

- https://github.com/containers/virtcontainers/blob/master/api.go#L34..L36 ?
