### ISSUE TITLE
Implement the runtime ps command

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#95]
`ps` shows all processes running inside a container.

**Comment by grahamwhaley** [comment]
A note and a question:
Note: if you do a `docker-runc ps xxx`, where xxx is not a valid container ID, then it prints out an error message noting that it could not find the relevant state.json file.  We of course don't have to copy this, but I found it interesting that we currently silently fail (with the correct exit code), whereas it looks like we could print something more useful.
Question: Is there a way to invoke the runtime ps command from the docker commandline? `docker ps` is something different (lists the containers, not their contents), and I've failed to identify if there is a way to get the container process list out of the docker command line. If we know of one, please update this ticket with that info.

**Comment by grahamwhaley** [comment]
Aha. The way to invoke the runtime `ps` from docker cli itself is by using `docker top` I believe.
Just checked, and this works for `runc`, but not for `cor` at least. I believe it will not work for `cc-runtime` at present either (I don't have an installation to hand to check right now)
