### ISSUE TITLE
Enable I/O PnP tests

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#97]
We'd like to be able to run the I/O (storage) metrics on CC3.x like we did for CC2.x.
We'd like to be able to run for local and remote volumes and rootfs.

**Comment by grahamwhaley** [comment]
IO tests were enabled with:
https://github.com/clearcontainers/tests/pull/225
and
https://github.com/clearcontainers/tests/pull/415

I've added a new Issue to cover the item of expanding these tests to cover the various mount types and storage (graph?) back ends:
https://github.com/clearcontainers/tests/issues/443
