### ISSUE TITLE
vendor: Follow new syntax for pruning with dep

### ISSUE THREAD

**Issue by sboeuf** [clearcontainers/runtime#974]
`dep` improved the way to prune by adding a tag in `Gopkg.toml` so that `dep ensure` will prune everything that needs to be pruned. No need to run `dep prune` anymore.

**Comment by jodh-intel** [comment]
Ah - I assume this is related to https://github.com/kata-containers/community/issues/20.

**Comment by sboeuf** [comment]
@jodh-intel yeah looks like it is !
