### ISSUE TITLE
Enable networking PnP tests

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#98]
We want to be able to run the networking metrics tests on CC3.x like we did for CC2.x

**Comment by grahamwhaley** [comment]
Directly related (and probably superseded by) https://github.com/clearcontainers/tests/issues/149

**Comment by grahamwhaley** [comment]
also see #39

**Comment by grahamwhaley** [comment]
PR landed to add the metrics tests. there are other PRs to automate the CI etc., so I'm closing this one.
https://github.com/clearcontainers/tests/pull/321
