### ISSUE TITLE
cri-o randomly fails by getting unexpected stdin

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/runtime#997]
# Description of problem

Recently on azure CI some cri-o test started to fail randomly all fails trying check an exacted output but ti does not exist.

Example:

```
17:21:43 not ok 13 ctr device add
17:21:43 # (in test file crio.bats, line 530)
17:21:43 #   `[[ "$output" =~ "/dev/mynull" ]]' failed
17:21:43 # 0
17:21:43 # time="2018-02-08 17:21:38.832696169Z" level=debug msg="[graphdriver] trying provided driver "devicemapper"" 
17:21:43 # time="2018-02-08 17:21:38.833122083Z" level=debug msg="devicemapper: kernel dm driver version is 4.37.0" 
17:21:43 # time="2018-02-08 17:21:38.833233487Z" level=debug msg="devmapper: Generated prefix: container-8:1-784941" 
17:21:43 # time="2018-02-08 17:21:38.833248687Z" level=debug msg="devmapper: Checking for existence of the pool container-8:1-784941-pool" 
17:21:43 # time="2018-02-08 17:21:38.833501096Z" level=debug msg="devmapper: Pool doesn't exist. Creating it." 
17:21:43 # time="2018-02-08 17:21:38.926425572Z" level=debug msg="devmapper: loadDeviceFilesOnStart()"
```

# Expected result

All cri-o test passing all the time and not fail randomly.

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `cc-collect-data.sh` script, after you have
reviewed its content to ensure it does not contain any private information).

**Comment by jcvenegas** [comment]
**cc** @sboeuf @chavafg

**Comment by sboeuf** [comment]
Thanks @jcvenegas !

**Comment by sboeuf** [comment]
First investigation make me think we have something wrong with the output of exec'ed  processes.

**Comment by erick0z** [comment]
@jcvenegas docker exec and cc-runtime exec does not print anything to stdout. I'm seeing the following error in the proxy logs:

```
time="2018-02-08T22:58:55.358961143Z" level=debug msg="{\\\"error\\\":\\\"read /dev/ptmx: file already closed\\\",\\\"level\\\":\\\"info\\\",\\\"msg\\\":\\\"Sequence has been closed\\\",\\\"name\\\":\\\"cc-agent\\\",\\\"pid\\\":133,\\\"sequence\\\":5,\\\"time\\\":\\\"2018-02-08T22:58:55.34883174Z\\\"}" name=cc-proxy pid=1688 source=qemu vm=28cb50ca4b82ffd917a2f026ea8981ad2183dab1538f465e2eaaa3bfa37eb5f5
```

**Comment by sboeuf** [comment]
@erick0z yeah I am working on a fix right now. I'll keep you posted about this issue.

**Comment by sboeuf** [comment]
Issue fixed here: https://github.com/clearcontainers/agent/pull/208
